2016/06/08 14:01:22 [error] [php] Use of undefined constant username - assumed 'username' (C:\xampp\htdocs\GatWebTest\protected\components\UserIdentity.php:21)
Stack trace:
#0 C:\xampp\htdocs\Yii\framework\validators\CValidator.php(201): CInlineValidator->validateAttribute()
#1 C:\xampp\htdocs\Yii\framework\base\CModel.php(159): CInlineValidator->validate()
#2 C:\xampp\htdocs\GatWebTest\protected\controllers\SiteController.php(94): LoginForm->validate()
#3 C:\xampp\htdocs\Yii\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#4 C:\xampp\htdocs\Yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#5 C:\xampp\htdocs\Yii\framework\web\CController.php(286): SiteController->runAction()
#6 C:\xampp\htdocs\Yii\framework\web\CController.php(265): SiteController->runActionWithFilters()
#7 C:\xampp\htdocs\Yii\framework\web\CWebApplication.php(282): SiteController->run()
#8 C:\xampp\htdocs\Yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#9 C:\xampp\htdocs\Yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#10 C:\xampp\htdocs\GatWebTest\index.php(13): CWebApplication->run()
REQUEST_URI=/gatwebtest/index.php?r=site/login
in C:\xampp\htdocs\GatWebTest\protected\components\UserIdentity.php (21)
in C:\xampp\htdocs\GatWebTest\protected\models\LoginForm.php (52)
in C:\xampp\htdocs\GatWebTest\protected\controllers\SiteController.php (94)
2016/06/08 14:02:20 [error] [php] Use of undefined constant username - assumed 'username' (C:\xampp\htdocs\GatWebTest\protected\components\UserIdentity.php:22)
Stack trace:
#0 C:\xampp\htdocs\Yii\framework\validators\CValidator.php(201): CInlineValidator->validateAttribute()
#1 C:\xampp\htdocs\Yii\framework\base\CModel.php(159): CInlineValidator->validate()
#2 C:\xampp\htdocs\GatWebTest\protected\controllers\SiteController.php(94): LoginForm->validate()
#3 C:\xampp\htdocs\Yii\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#4 C:\xampp\htdocs\Yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#5 C:\xampp\htdocs\Yii\framework\web\CController.php(286): SiteController->runAction()
#6 C:\xampp\htdocs\Yii\framework\web\CController.php(265): SiteController->runActionWithFilters()
#7 C:\xampp\htdocs\Yii\framework\web\CWebApplication.php(282): SiteController->run()
#8 C:\xampp\htdocs\Yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#9 C:\xampp\htdocs\Yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#10 C:\xampp\htdocs\GatWebTest\index.php(13): CWebApplication->run()
REQUEST_URI=/gatwebtest/index.php?r=site/login
in C:\xampp\htdocs\GatWebTest\protected\components\UserIdentity.php (22)
in C:\xampp\htdocs\GatWebTest\protected\models\LoginForm.php (52)
in C:\xampp\htdocs\GatWebTest\protected\controllers\SiteController.php (94)
2016/06/08 14:03:27 [error] [php] Undefined variable: password (C:\xampp\htdocs\GatWebTest\protected\components\UserIdentity.php:22)
Stack trace:
#0 C:\xampp\htdocs\Yii\framework\validators\CValidator.php(201): CInlineValidator->validateAttribute()
#1 C:\xampp\htdocs\Yii\framework\base\CModel.php(159): CInlineValidator->validate()
#2 C:\xampp\htdocs\GatWebTest\protected\controllers\SiteController.php(94): LoginForm->validate()
#3 C:\xampp\htdocs\Yii\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#4 C:\xampp\htdocs\Yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#5 C:\xampp\htdocs\Yii\framework\web\CController.php(286): SiteController->runAction()
#6 C:\xampp\htdocs\Yii\framework\web\CController.php(265): SiteController->runActionWithFilters()
#7 C:\xampp\htdocs\Yii\framework\web\CWebApplication.php(282): SiteController->run()
#8 C:\xampp\htdocs\Yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#9 C:\xampp\htdocs\Yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#10 C:\xampp\htdocs\GatWebTest\index.php(13): CWebApplication->run()
REQUEST_URI=/gatwebtest/index.php?r=site/login
in C:\xampp\htdocs\GatWebTest\protected\components\UserIdentity.php (22)
in C:\xampp\htdocs\GatWebTest\protected\models\LoginForm.php (52)
in C:\xampp\htdocs\GatWebTest\protected\controllers\SiteController.php (94)
2016/06/08 14:04:19 [error] [php] Undefined variable: password (C:\xampp\htdocs\GatWebTest\protected\components\UserIdentity.php:22)
Stack trace:
#0 C:\xampp\htdocs\Yii\framework\validators\CValidator.php(201): CInlineValidator->validateAttribute()
#1 C:\xampp\htdocs\Yii\framework\base\CModel.php(159): CInlineValidator->validate()
#2 C:\xampp\htdocs\GatWebTest\protected\controllers\SiteController.php(94): LoginForm->validate()
#3 C:\xampp\htdocs\Yii\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#4 C:\xampp\htdocs\Yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#5 C:\xampp\htdocs\Yii\framework\web\CController.php(286): SiteController->runAction()
#6 C:\xampp\htdocs\Yii\framework\web\CController.php(265): SiteController->runActionWithFilters()
#7 C:\xampp\htdocs\Yii\framework\web\CWebApplication.php(282): SiteController->run()
#8 C:\xampp\htdocs\Yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#9 C:\xampp\htdocs\Yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#10 C:\xampp\htdocs\GatWebTest\index.php(13): CWebApplication->run()
REQUEST_URI=/gatwebtest/index.php?r=site/login
in C:\xampp\htdocs\GatWebTest\protected\components\UserIdentity.php (22)
in C:\xampp\htdocs\GatWebTest\protected\models\LoginForm.php (52)
in C:\xampp\htdocs\GatWebTest\protected\controllers\SiteController.php (94)
2016/06/08 14:19:03 [error] [php] Undefined variable: password (C:\xampp\htdocs\GatWebTest\protected\components\UserIdentity.php:22)
Stack trace:
#0 C:\xampp\htdocs\Yii\framework\validators\CValidator.php(201): CInlineValidator->validateAttribute()
#1 C:\xampp\htdocs\Yii\framework\base\CModel.php(159): CInlineValidator->validate()
#2 C:\xampp\htdocs\GatWebTest\protected\controllers\SiteController.php(94): LoginForm->validate()
#3 C:\xampp\htdocs\Yii\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#4 C:\xampp\htdocs\Yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#5 C:\xampp\htdocs\Yii\framework\web\CController.php(286): SiteController->runAction()
#6 C:\xampp\htdocs\Yii\framework\web\CController.php(265): SiteController->runActionWithFilters()
#7 C:\xampp\htdocs\Yii\framework\web\CWebApplication.php(282): SiteController->run()
#8 C:\xampp\htdocs\Yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#9 C:\xampp\htdocs\Yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#10 C:\xampp\htdocs\GatWebTest\index.php(13): CWebApplication->run()
REQUEST_URI=/gatwebtest/index.php?r=site/login
in C:\xampp\htdocs\GatWebTest\protected\components\UserIdentity.php (22)
in C:\xampp\htdocs\GatWebTest\protected\models\LoginForm.php (52)
in C:\xampp\htdocs\GatWebTest\protected\controllers\SiteController.php (94)
2016/06/08 14:21:50 [error] [php] include(User.php): failed to open stream: No such file or directory (C:\xampp\htdocs\Yii\framework\YiiBase.php:432)
Stack trace:
#0 C:\xampp\htdocs\GatWebTest\protected\components\UserIdentity.php(21): spl_autoload_call()
#1 C:\xampp\htdocs\GatWebTest\protected\models\LoginForm.php(52): UserIdentity->authenticate()
#2 C:\xampp\htdocs\Yii\framework\validators\CInlineValidator.php(42): LoginForm->authenticate()
#3 C:\xampp\htdocs\Yii\framework\validators\CValidator.php(201): CInlineValidator->validateAttribute()
#4 C:\xampp\htdocs\Yii\framework\base\CModel.php(159): CInlineValidator->validate()
#5 C:\xampp\htdocs\GatWebTest\protected\controllers\SiteController.php(94): LoginForm->validate()
#6 C:\xampp\htdocs\Yii\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#7 C:\xampp\htdocs\Yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#8 C:\xampp\htdocs\Yii\framework\web\CController.php(286): SiteController->runAction()
#9 C:\xampp\htdocs\Yii\framework\web\CController.php(265): SiteController->runActionWithFilters()
#10 C:\xampp\htdocs\Yii\framework\web\CWebApplication.php(282): SiteController->run()
#11 C:\xampp\htdocs\Yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#12 C:\xampp\htdocs\Yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#13 C:\xampp\htdocs\GatWebTest\index.php(13): CWebApplication->run()
REQUEST_URI=/gatwebtest/index.php?r=site/login
in C:\xampp\htdocs\GatWebTest\protected\components\UserIdentity.php (21)
in C:\xampp\htdocs\GatWebTest\protected\models\LoginForm.php (52)
in C:\xampp\htdocs\GatWebTest\protected\controllers\SiteController.php (94)
2016/06/08 14:22:07 [error] [php] include(User.php): failed to open stream: No such file or directory (C:\xampp\htdocs\Yii\framework\YiiBase.php:432)
Stack trace:
#0 C:\xampp\htdocs\GatWebTest\protected\components\UserIdentity.php(21): spl_autoload_call()
#1 C:\xampp\htdocs\GatWebTest\protected\models\LoginForm.php(52): UserIdentity->authenticate()
#2 C:\xampp\htdocs\Yii\framework\validators\CInlineValidator.php(42): LoginForm->authenticate()
#3 C:\xampp\htdocs\Yii\framework\validators\CValidator.php(201): CInlineValidator->validateAttribute()
#4 C:\xampp\htdocs\Yii\framework\base\CModel.php(159): CInlineValidator->validate()
#5 C:\xampp\htdocs\GatWebTest\protected\controllers\SiteController.php(94): LoginForm->validate()
#6 C:\xampp\htdocs\Yii\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#7 C:\xampp\htdocs\Yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#8 C:\xampp\htdocs\Yii\framework\web\CController.php(286): SiteController->runAction()
#9 C:\xampp\htdocs\Yii\framework\web\CController.php(265): SiteController->runActionWithFilters()
#10 C:\xampp\htdocs\Yii\framework\web\CWebApplication.php(282): SiteController->run()
#11 C:\xampp\htdocs\Yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#12 C:\xampp\htdocs\Yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#13 C:\xampp\htdocs\GatWebTest\index.php(13): CWebApplication->run()
REQUEST_URI=/gatwebtest/index.php?r=site/login
in C:\xampp\htdocs\GatWebTest\protected\components\UserIdentity.php (21)
in C:\xampp\htdocs\GatWebTest\protected\models\LoginForm.php (52)
in C:\xampp\htdocs\GatWebTest\protected\controllers\SiteController.php (94)
2016/06/08 14:22:19 [error] [php] include(User.php): failed to open stream: No such file or directory (C:\xampp\htdocs\Yii\framework\YiiBase.php:432)
Stack trace:
#0 C:\xampp\htdocs\GatWebTest\protected\components\UserIdentity.php(21): spl_autoload_call()
#1 C:\xampp\htdocs\GatWebTest\protected\models\LoginForm.php(52): UserIdentity->authenticate()
#2 C:\xampp\htdocs\Yii\framework\validators\CInlineValidator.php(42): LoginForm->authenticate()
#3 C:\xampp\htdocs\Yii\framework\validators\CValidator.php(201): CInlineValidator->validateAttribute()
#4 C:\xampp\htdocs\Yii\framework\base\CModel.php(159): CInlineValidator->validate()
#5 C:\xampp\htdocs\GatWebTest\protected\controllers\SiteController.php(94): LoginForm->validate()
#6 C:\xampp\htdocs\Yii\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#7 C:\xampp\htdocs\Yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#8 C:\xampp\htdocs\Yii\framework\web\CController.php(286): SiteController->runAction()
#9 C:\xampp\htdocs\Yii\framework\web\CController.php(265): SiteController->runActionWithFilters()
#10 C:\xampp\htdocs\Yii\framework\web\CWebApplication.php(282): SiteController->run()
#11 C:\xampp\htdocs\Yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#12 C:\xampp\htdocs\Yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#13 C:\xampp\htdocs\GatWebTest\index.php(13): CWebApplication->run()
REQUEST_URI=/gatwebtest/index.php?r=site/login
in C:\xampp\htdocs\GatWebTest\protected\components\UserIdentity.php (21)
in C:\xampp\htdocs\GatWebTest\protected\models\LoginForm.php (52)
in C:\xampp\htdocs\GatWebTest\protected\controllers\SiteController.php (94)
2016/06/08 14:22:33 [error] [exception.CException] exception 'CException' with message 'Property "UserIdentity.username" is not defined.' in C:\xampp\htdocs\Yii\framework\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\GatWebTest\protected\components\UserIdentity.php(21): CComponent->__get('username')
#1 C:\xampp\htdocs\GatWebTest\protected\models\LoginForm.php(52): UserIdentity->authenticate()
#2 C:\xampp\htdocs\Yii\framework\validators\CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#3 C:\xampp\htdocs\Yii\framework\validators\CValidator.php(201): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#4 C:\xampp\htdocs\Yii\framework\base\CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#5 C:\xampp\htdocs\GatWebTest\protected\controllers\SiteController.php(94): CModel->validate()
#6 C:\xampp\htdocs\Yii\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#7 C:\xampp\htdocs\Yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#8 C:\xampp\htdocs\Yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#9 C:\xampp\htdocs\Yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#10 C:\xampp\htdocs\Yii\framework\web\CWebApplication.php(282): CController->run('login')
#11 C:\xampp\htdocs\Yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/login')
#12 C:\xampp\htdocs\Yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#13 C:\xampp\htdocs\GatWebTest\index.php(13): CApplication->run()
#14 {main}
REQUEST_URI=/gatwebtest/index.php?r=site/login
HTTP_REFERER=http://localhost/gatwebtest/index.php?r=site/login
---
2016/06/08 14:30:15 [error] [exception.CException] exception 'CException' with message 'Property "UserIdentity.username" is not defined.' in C:\xampp\htdocs\Yii\framework\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\GatWebTest\protected\components\UserIdentity.php(15): CComponent->__get('username')
#1 C:\xampp\htdocs\GatWebTest\protected\models\LoginForm.php(52): UserIdentity->authenticate()
#2 C:\xampp\htdocs\Yii\framework\validators\CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#3 C:\xampp\htdocs\Yii\framework\validators\CValidator.php(201): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#4 C:\xampp\htdocs\Yii\framework\base\CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#5 C:\xampp\htdocs\GatWebTest\protected\controllers\SiteController.php(94): CModel->validate()
#6 C:\xampp\htdocs\Yii\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#7 C:\xampp\htdocs\Yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#8 C:\xampp\htdocs\Yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#9 C:\xampp\htdocs\Yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#10 C:\xampp\htdocs\Yii\framework\web\CWebApplication.php(282): CController->run('login')
#11 C:\xampp\htdocs\Yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/login')
#12 C:\xampp\htdocs\Yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#13 C:\xampp\htdocs\GatWebTest\index.php(13): CApplication->run()
#14 {main}
REQUEST_URI=/gatwebtest/index.php?r=site/login
HTTP_REFERER=http://localhost/gatwebtest/index.php?r=site/login
---
2016/06/08 14:41:50 [error] [exception.CException] exception 'CException' with message 'Property "Account.id" is not defined.' in C:\xampp\htdocs\Yii\framework\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\Yii\framework\db\ar\CActiveRecord.php(145): CComponent->__get('id')
#1 C:\xampp\htdocs\GatWebTest\protected\components\UserIdentity.php(23): CActiveRecord->__get('id')
#2 C:\xampp\htdocs\GatWebTest\protected\models\LoginForm.php(52): UserIdentity->authenticate()
#3 C:\xampp\htdocs\Yii\framework\validators\CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#4 C:\xampp\htdocs\Yii\framework\validators\CValidator.php(201): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#5 C:\xampp\htdocs\Yii\framework\base\CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#6 C:\xampp\htdocs\GatWebTest\protected\controllers\SiteController.php(94): CModel->validate()
#7 C:\xampp\htdocs\Yii\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#8 C:\xampp\htdocs\Yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#9 C:\xampp\htdocs\Yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#10 C:\xampp\htdocs\Yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 C:\xampp\htdocs\Yii\framework\web\CWebApplication.php(282): CController->run('login')
#12 C:\xampp\htdocs\Yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/login')
#13 C:\xampp\htdocs\Yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#14 C:\xampp\htdocs\GatWebTest\index.php(13): CApplication->run()
#15 {main}
REQUEST_URI=/gatwebtest/index.php?r=site/login
HTTP_REFERER=http://localhost/gatwebtest/index.php?r=site/login
---
2016/06/08 14:42:15 [error] [exception.CException] exception 'CException' with message 'Property "Account.id" is not defined.' in C:\xampp\htdocs\Yii\framework\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\Yii\framework\db\ar\CActiveRecord.php(145): CComponent->__get('id')
#1 C:\xampp\htdocs\GatWebTest\protected\components\UserIdentity.php(24): CActiveRecord->__get('id')
#2 C:\xampp\htdocs\GatWebTest\protected\models\LoginForm.php(52): UserIdentity->authenticate()
#3 C:\xampp\htdocs\Yii\framework\validators\CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#4 C:\xampp\htdocs\Yii\framework\validators\CValidator.php(201): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#5 C:\xampp\htdocs\Yii\framework\base\CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#6 C:\xampp\htdocs\GatWebTest\protected\controllers\SiteController.php(94): CModel->validate()
#7 C:\xampp\htdocs\Yii\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#8 C:\xampp\htdocs\Yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#9 C:\xampp\htdocs\Yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#10 C:\xampp\htdocs\Yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 C:\xampp\htdocs\Yii\framework\web\CWebApplication.php(282): CController->run('login')
#12 C:\xampp\htdocs\Yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/login')
#13 C:\xampp\htdocs\Yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#14 C:\xampp\htdocs\GatWebTest\index.php(13): CApplication->run()
#15 {main}
REQUEST_URI=/gatwebtest/index.php?r=site/login
HTTP_REFERER=http://localhost/gatwebtest/index.php?r=site/login
---
2016/06/08 14:42:33 [error] [exception.CException] exception 'CException' with message 'Property "Account.id" is not defined.' in C:\xampp\htdocs\Yii\framework\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\Yii\framework\db\ar\CActiveRecord.php(145): CComponent->__get('id')
#1 C:\xampp\htdocs\GatWebTest\protected\components\UserIdentity.php(24): CActiveRecord->__get('id')
#2 C:\xampp\htdocs\GatWebTest\protected\models\LoginForm.php(52): UserIdentity->authenticate()
#3 C:\xampp\htdocs\Yii\framework\validators\CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#4 C:\xampp\htdocs\Yii\framework\validators\CValidator.php(201): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#5 C:\xampp\htdocs\Yii\framework\base\CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#6 C:\xampp\htdocs\GatWebTest\protected\controllers\SiteController.php(94): CModel->validate()
#7 C:\xampp\htdocs\Yii\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#8 C:\xampp\htdocs\Yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#9 C:\xampp\htdocs\Yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#10 C:\xampp\htdocs\Yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 C:\xampp\htdocs\Yii\framework\web\CWebApplication.php(282): CController->run('login')
#12 C:\xampp\htdocs\Yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/login')
#13 C:\xampp\htdocs\Yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#14 C:\xampp\htdocs\GatWebTest\index.php(13): CApplication->run()
#15 {main}
REQUEST_URI=/gatwebtest/index.php?r=site/login
HTTP_REFERER=http://localhost/gatwebtest/index.php?r=site/login
---
2016/06/08 14:53:08 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "register".' in C:\xampp\htdocs\Yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\Yii\framework\web\CController.php(270): CController->missingAction('register')
#1 C:\xampp\htdocs\Yii\framework\web\CWebApplication.php(282): CController->run('register')
#2 C:\xampp\htdocs\Yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/register')
#3 C:\xampp\htdocs\Yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 C:\xampp\htdocs\GatWebTest\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/gatwebtest/index.php?r=site/register
HTTP_REFERER=http://localhost/gatwebtest/index.php?r=site/page&view=about
---
2016/06/10 14:57:08 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "account".' in C:\xampp\htdocs\Yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\Yii\framework\web\CController.php(270): CController->missingAction('account')
#1 C:\xampp\htdocs\Yii\framework\web\CWebApplication.php(282): CController->run('account')
#2 C:\xampp\htdocs\Yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/account')
#3 C:\xampp\htdocs\Yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 C:\xampp\htdocs\GatWebTest\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/gatwebtest/index.php?r=site/account
---
2016/06/10 15:02:39 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\Yii\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\Yii\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 C:\xampp\htdocs\Yii\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\Yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\Yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\Yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\Yii\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\Yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\Yii\framework\web\CWebApplication.php(282): CController->run('admin')
#8 C:\xampp\htdocs\Yii\framework\web\CWebApplication.php(141): CWebApplication->runController('account/admin')
#9 C:\xampp\htdocs\Yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#10 C:\xampp\htdocs\GatWebTest\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/gatwebtest/index.php?r=account/admin
HTTP_REFERER=http://localhost:81/gatwebtest/index.php?r=account/index
---
2016/06/10 15:03:18 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\Yii\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\Yii\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 C:\xampp\htdocs\Yii\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\Yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\Yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\Yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\Yii\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\Yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\Yii\framework\web\CWebApplication.php(282): CController->run('admin')
#8 C:\xampp\htdocs\Yii\framework\web\CWebApplication.php(141): CWebApplication->runController('account/admin')
#9 C:\xampp\htdocs\Yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#10 C:\xampp\htdocs\GatWebTest\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/gatwebtest/index.php?r=account/admin
HTTP_REFERER=http://localhost:81/gatwebtest/index.php?r=account/index
---
2016/06/10 15:06:00 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Your request is invalid.' in C:\xampp\htdocs\Yii\framework\web\CController.php:336
Stack trace:
#0 C:\xampp\htdocs\Yii\framework\web\CController.php(309): CController->invalidActionParams(Object(CInlineAction))
#1 C:\xampp\htdocs\Yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#2 C:\xampp\htdocs\Yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#3 C:\xampp\htdocs\Yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#4 C:\xampp\htdocs\Yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#5 C:\xampp\htdocs\Yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#6 C:\xampp\htdocs\Yii\framework\web\CController.php(291): CFilterChain->run()
#7 C:\xampp\htdocs\Yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 C:\xampp\htdocs\Yii\framework\web\CWebApplication.php(282): CController->run('view')
#9 C:\xampp\htdocs\Yii\framework\web\CWebApplication.php(141): CWebApplication->runController('account/view')
#10 C:\xampp\htdocs\Yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#11 C:\xampp\htdocs\GatWebTest\index.php(13): CApplication->run()
#12 {main}
REQUEST_URI=/gatwebtest/index.php?r=account/view
---
2016/06/10 15:06:17 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Your request is invalid.' in C:\xampp\htdocs\Yii\framework\web\CController.php:336
Stack trace:
#0 C:\xampp\htdocs\Yii\framework\web\CController.php(309): CController->invalidActionParams(Object(CInlineAction))
#1 C:\xampp\htdocs\Yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#2 C:\xampp\htdocs\Yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#3 C:\xampp\htdocs\Yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#4 C:\xampp\htdocs\Yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#5 C:\xampp\htdocs\Yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#6 C:\xampp\htdocs\Yii\framework\web\CController.php(291): CFilterChain->run()
#7 C:\xampp\htdocs\Yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 C:\xampp\htdocs\Yii\framework\web\CWebApplication.php(282): CController->run('update')
#9 C:\xampp\htdocs\Yii\framework\web\CWebApplication.php(141): CWebApplication->runController('account/update')
#10 C:\xampp\htdocs\Yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#11 C:\xampp\htdocs\GatWebTest\index.php(13): CApplication->run()
#12 {main}
REQUEST_URI=/gatwebtest/index.php?r=account/update
---
2016/06/10 15:06:25 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\Yii\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\Yii\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 C:\xampp\htdocs\Yii\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\Yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\Yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\Yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\Yii\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\Yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\Yii\framework\web\CWebApplication.php(282): CController->run('admin')
#8 C:\xampp\htdocs\Yii\framework\web\CWebApplication.php(141): CWebApplication->runController('account/admin')
#9 C:\xampp\htdocs\Yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#10 C:\xampp\htdocs\GatWebTest\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/gatwebtest/index.php?r=account/admin
---
2016/06/10 15:06:48 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "_search".' in C:\xampp\htdocs\Yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\Yii\framework\web\CController.php(270): CController->missingAction('_search')
#1 C:\xampp\htdocs\Yii\framework\web\CWebApplication.php(282): CController->run('_search')
#2 C:\xampp\htdocs\Yii\framework\web\CWebApplication.php(141): CWebApplication->runController('account/_search')
#3 C:\xampp\htdocs\Yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 C:\xampp\htdocs\GatWebTest\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/gatwebtest/index.php?r=account/_search
---
2016/06/10 15:21:09 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The requested page does not exist.' in C:\xampp\htdocs\GatWebTest\protected\controllers\AccountController.php:157
Stack trace:
#0 C:\xampp\htdocs\GatWebTest\protected\controllers\AccountController.php(55): AccountController->loadModel('8')
#1 [internal function]: AccountController->actionView('8')
#2 C:\xampp\htdocs\Yii\framework\web\actions\CAction.php(109): ReflectionMethod->invokeArgs(Object(AccountController), Array)
#3 C:\xampp\htdocs\Yii\framework\web\actions\CInlineAction.php(47): CAction->runWithParamsInternal(Object(AccountController), Object(ReflectionMethod), Array)
#4 C:\xampp\htdocs\Yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 C:\xampp\htdocs\Yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#6 C:\xampp\htdocs\Yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#7 C:\xampp\htdocs\Yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#8 C:\xampp\htdocs\Yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#9 C:\xampp\htdocs\Yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#10 C:\xampp\htdocs\Yii\framework\web\CController.php(291): CFilterChain->run()
#11 C:\xampp\htdocs\Yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\xampp\htdocs\Yii\framework\web\CWebApplication.php(282): CController->run('view')
#13 C:\xampp\htdocs\Yii\framework\web\CWebApplication.php(141): CWebApplication->runController('account/view')
#14 C:\xampp\htdocs\Yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#15 C:\xampp\htdocs\GatWebTest\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/gatwebtest/index.php?r=account/view&id=8
---
2016/06/10 15:23:32 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\Yii\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\Yii\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 C:\xampp\htdocs\Yii\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\Yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\Yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\Yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\Yii\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\Yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\Yii\framework\web\CWebApplication.php(282): CController->run('admin')
#8 C:\xampp\htdocs\Yii\framework\web\CWebApplication.php(141): CWebApplication->runController('account/admin')
#9 C:\xampp\htdocs\Yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#10 C:\xampp\htdocs\GatWebTest\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/gatwebtest/index.php?r=account/admin
HTTP_REFERER=http://localhost:81/gatwebtest/index.php?r=account/view&id=4
---
2016/06/10 15:39:25 [error] [php] Array to string conversion (C:\xampp\htdocs\GatWebTest\protected\views\account\_view.php:9)
Stack trace:
#0 C:\xampp\htdocs\Yii\framework\zii\widgets\CListView.php(291): AccountController->renderFile()
#1 C:\xampp\htdocs\Yii\framework\zii\widgets\CBaseListView.php(181): CListView->renderItems()
#2 unknown(0): CListView->renderSection()
#3 C:\xampp\htdocs\Yii\framework\zii\widgets\CBaseListView.php(164): preg_replace_callback()
#4 C:\xampp\htdocs\Yii\framework\zii\widgets\CBaseListView.php(149): CListView->renderContent()
#5 C:\xampp\htdocs\Yii\framework\web\CBaseController.php(181): CListView->run()
#6 C:\xampp\htdocs\GatWebTest\protected\views\account\index.php(20): AccountController->widget()
#7 C:\xampp\htdocs\Yii\framework\web\CBaseController.php(126): require()
#8 C:\xampp\htdocs\Yii\framework\web\CBaseController.php(95): AccountController->renderInternal()
#9 C:\xampp\htdocs\Yii\framework\web\CController.php(869): AccountController->renderFile()
#10 C:\xampp\htdocs\Yii\framework\web\CController.php(782): AccountController->renderPartial()
#11 C:\xampp\htdocs\GatWebTest\protected\controllers\AccountController.php(128): AccountController->render()
#12 C:\xampp\htdocs\Yii\framework\web\actions\CInlineAction.php(49): AccountController->actionIndex()
#13 C:\xampp\htdocs\Yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#14 C:\xampp\htdocs\Yii\framework\web\filters\CFilterChain.php(133): AccountController->runAction()
#15 C:\xampp\htdocs\Yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#16 C:\xampp\htdocs\Yii\framework\web\CController.php(1145): CAccessControlFilter->filter()
#17 C:\xampp\htdocs\Yii\framework\web\filters\CInlineFilter.php(58): AccountController->filterAccessControl()
#18 C:\xampp\htdocs\Yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#19 C:\xampp\htdocs\Yii\framework\web\CController.php(291): CFilterChain->run()
#20 C:\xampp\htdocs\Yii\framework\web\CController.php(265): AccountController->runActionWithFilters()
#21 C:\xampp\htdocs\Yii\framework\web\CWebApplication.php(282): AccountController->run()
#22 C:\xampp\htdocs\Yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#23 C:\xampp\htdocs\Yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#24 C:\xampp\htdocs\GatWebTest\index.php(13): CWebApplication->run()
REQUEST_URI=/gatwebtest/index.php?r=account/index
in C:\xampp\htdocs\GatWebTest\protected\views\account\_view.php (9)
in C:\xampp\htdocs\GatWebTest\protected\views\account\index.php (20)
in C:\xampp\htdocs\GatWebTest\protected\controllers\AccountController.php (128)
2016/06/10 15:39:57 [error] [php] Array to string conversion (C:\xampp\htdocs\GatWebTest\protected\views\account\_view.php:9)
Stack trace:
#0 C:\xampp\htdocs\Yii\framework\zii\widgets\CListView.php(291): AccountController->renderFile()
#1 C:\xampp\htdocs\Yii\framework\zii\widgets\CBaseListView.php(181): CListView->renderItems()
#2 unknown(0): CListView->renderSection()
#3 C:\xampp\htdocs\Yii\framework\zii\widgets\CBaseListView.php(164): preg_replace_callback()
#4 C:\xampp\htdocs\Yii\framework\zii\widgets\CBaseListView.php(149): CListView->renderContent()
#5 C:\xampp\htdocs\Yii\framework\web\CBaseController.php(181): CListView->run()
#6 C:\xampp\htdocs\GatWebTest\protected\views\account\index.php(20): AccountController->widget()
#7 C:\xampp\htdocs\Yii\framework\web\CBaseController.php(126): require()
#8 C:\xampp\htdocs\Yii\framework\web\CBaseController.php(95): AccountController->renderInternal()
#9 C:\xampp\htdocs\Yii\framework\web\CController.php(869): AccountController->renderFile()
#10 C:\xampp\htdocs\Yii\framework\web\CController.php(782): AccountController->renderPartial()
#11 C:\xampp\htdocs\GatWebTest\protected\controllers\AccountController.php(128): AccountController->render()
#12 C:\xampp\htdocs\Yii\framework\web\actions\CInlineAction.php(49): AccountController->actionIndex()
#13 C:\xampp\htdocs\Yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#14 C:\xampp\htdocs\Yii\framework\web\filters\CFilterChain.php(133): AccountController->runAction()
#15 C:\xampp\htdocs\Yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#16 C:\xampp\htdocs\Yii\framework\web\CController.php(1145): CAccessControlFilter->filter()
#17 C:\xampp\htdocs\Yii\framework\web\filters\CInlineFilter.php(58): AccountController->filterAccessControl()
#18 C:\xampp\htdocs\Yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#19 C:\xampp\htdocs\Yii\framework\web\CController.php(291): CFilterChain->run()
#20 C:\xampp\htdocs\Yii\framework\web\CController.php(265): AccountController->runActionWithFilters()
#21 C:\xampp\htdocs\Yii\framework\web\CWebApplication.php(282): AccountController->run()
#22 C:\xampp\htdocs\Yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#23 C:\xampp\htdocs\Yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#24 C:\xampp\htdocs\GatWebTest\index.php(13): CWebApplication->run()
REQUEST_URI=/gatwebtest/index.php?r=account/index
in C:\xampp\htdocs\GatWebTest\protected\views\account\_view.php (9)
in C:\xampp\htdocs\GatWebTest\protected\views\account\index.php (20)
in C:\xampp\htdocs\GatWebTest\protected\controllers\AccountController.php (128)
2016/06/10 15:53:04 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Your request is invalid.' in C:\xampp\htdocs\Yii\framework\web\CController.php:336
Stack trace:
#0 C:\xampp\htdocs\Yii\framework\web\CController.php(309): CController->invalidActionParams(Object(CInlineAction))
#1 C:\xampp\htdocs\Yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#2 C:\xampp\htdocs\Yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#3 C:\xampp\htdocs\Yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#4 C:\xampp\htdocs\Yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#5 C:\xampp\htdocs\Yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#6 C:\xampp\htdocs\Yii\framework\web\CController.php(291): CFilterChain->run()
#7 C:\xampp\htdocs\Yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 C:\xampp\htdocs\Yii\framework\web\CWebApplication.php(282): CController->run('update')
#9 C:\xampp\htdocs\Yii\framework\web\CWebApplication.php(141): CWebApplication->runController('account/update')
#10 C:\xampp\htdocs\Yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#11 C:\xampp\htdocs\GatWebTest\index.php(13): CApplication->run()
#12 {main}
REQUEST_URI=/gatwebtest/index.php?r=account/update
---
2016/06/10 15:53:26 [error] [exception.CHttpException.400] exception 'CHttpException' with message 'Your request is invalid.' in C:\xampp\htdocs\Yii\framework\web\CController.php:336
Stack trace:
#0 C:\xampp\htdocs\Yii\framework\web\CController.php(309): CController->invalidActionParams(Object(CInlineAction))
#1 C:\xampp\htdocs\Yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#2 C:\xampp\htdocs\Yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#3 C:\xampp\htdocs\Yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#4 C:\xampp\htdocs\Yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#5 C:\xampp\htdocs\Yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#6 C:\xampp\htdocs\Yii\framework\web\CController.php(291): CFilterChain->run()
#7 C:\xampp\htdocs\Yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 C:\xampp\htdocs\Yii\framework\web\CWebApplication.php(282): CController->run('update')
#9 C:\xampp\htdocs\Yii\framework\web\CWebApplication.php(141): CWebApplication->runController('account/update')
#10 C:\xampp\htdocs\Yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#11 C:\xampp\htdocs\GatWebTest\index.php(13): CApplication->run()
#12 {main}
REQUEST_URI=/gatwebtest/index.php?r=account/update
---
2016/06/10 15:53:30 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\Yii\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\Yii\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 C:\xampp\htdocs\Yii\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\Yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\Yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\Yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\Yii\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\Yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\Yii\framework\web\CWebApplication.php(282): CController->run('delete')
#8 C:\xampp\htdocs\Yii\framework\web\CWebApplication.php(141): CWebApplication->runController('account/delete')
#9 C:\xampp\htdocs\Yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#10 C:\xampp\htdocs\GatWebTest\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/gatwebtest/index.php?r=account/delete
---
2016/06/10 15:53:38 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\Yii\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\Yii\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 C:\xampp\htdocs\Yii\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\Yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\Yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\Yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\Yii\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\Yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\Yii\framework\web\CWebApplication.php(282): CController->run('admin')
#8 C:\xampp\htdocs\Yii\framework\web\CWebApplication.php(141): CWebApplication->runController('account/admin')
#9 C:\xampp\htdocs\Yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#10 C:\xampp\htdocs\GatWebTest\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/gatwebtest/index.php?r=account/admin
---
2016/06/10 16:00:11 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "layout/main".' in C:\xampp\htdocs\Yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\Yii\framework\web\CWebApplication.php(141): CWebApplication->runController('layout/main')
#1 C:\xampp\htdocs\Yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\GatWebTest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/gatwebtest/index.php?r=layout/main
---
2016/06/10 16:01:10 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "page/about".' in C:\xampp\htdocs\Yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\Yii\framework\web\CWebApplication.php(141): CWebApplication->runController('page/about')
#1 C:\xampp\htdocs\Yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\GatWebTest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/gatwebtest/index.php?r=page/about
---
2016/06/10 16:01:15 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "page".' in C:\xampp\htdocs\Yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\Yii\framework\web\CWebApplication.php(141): CWebApplication->runController('page')
#1 C:\xampp\htdocs\Yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\GatWebTest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/gatwebtest/index.php?r=page
---
2016/06/10 16:01:27 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "pages/".' in C:\xampp\htdocs\Yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\Yii\framework\web\CWebApplication.php(141): CWebApplication->runController('pages/')
#1 C:\xampp\htdocs\Yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\GatWebTest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/gatwebtest/index.php?r=pages/
---
2016/06/10 16:01:36 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "pages/about".' in C:\xampp\htdocs\Yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\Yii\framework\web\CWebApplication.php(141): CWebApplication->runController('pages/about')
#1 C:\xampp\htdocs\Yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\GatWebTest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/gatwebtest/index.php?r=pages/about
---
2016/06/10 16:01:42 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "pages/about.php".' in C:\xampp\htdocs\Yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\Yii\framework\web\CWebApplication.php(141): CWebApplication->runController('pages/about.php')
#1 C:\xampp\htdocs\Yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\GatWebTest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/gatwebtest/index.php?r=pages/about.php
---
2016/06/10 16:01:52 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "pages/".' in C:\xampp\htdocs\Yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\Yii\framework\web\CWebApplication.php(141): CWebApplication->runController('pages/')
#1 C:\xampp\htdocs\Yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\GatWebTest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/gatwebtest/index.php?r=pages/
---
2016/06/13 08:45:33 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "saccos".' in C:\xampp\htdocs\Yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\Yii\framework\web\CController.php(270): CController->missingAction('saccos')
#1 C:\xampp\htdocs\Yii\framework\web\CWebApplication.php(282): CController->run('saccos')
#2 C:\xampp\htdocs\Yii\framework\web\CWebApplication.php(141): CWebApplication->runController('sacco/saccos')
#3 C:\xampp\htdocs\Yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#4 C:\xampp\htdocs\GatWebTest\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/gatwebtest/index.php?r=sacco/saccos
---
2016/06/13 08:46:07 [error] [exception.CException] exception 'CException' with message 'SaccoController and its behaviors do not have a method or closure named "rander".' in C:\xampp\htdocs\Yii\framework\base\CComponent.php:266
Stack trace:
#0 C:\xampp\htdocs\GatWebTest\protected\controllers\SaccoController.php(39): CComponent->__call('rander', Array)
#1 C:\xampp\htdocs\GatWebTest\protected\controllers\SaccoController.php(39): SaccoController->rander('saccos')
#2 C:\xampp\htdocs\Yii\framework\web\actions\CInlineAction.php(49): SaccoController->actionViewSacco()
#3 C:\xampp\htdocs\Yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#4 C:\xampp\htdocs\Yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#5 C:\xampp\htdocs\Yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 C:\xampp\htdocs\Yii\framework\web\CWebApplication.php(282): CController->run('ViewSacco')
#7 C:\xampp\htdocs\Yii\framework\web\CWebApplication.php(141): CWebApplication->runController('sacco/ViewSacco')
#8 C:\xampp\htdocs\Yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#9 C:\xampp\htdocs\GatWebTest\index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/gatwebtest/index.php?r=sacco/ViewSacco
---
2016/06/13 08:56:27 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "index".' in C:\xampp\htdocs\Yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\Yii\framework\web\CWebApplication.php(141): CWebApplication->runController('index')
#1 C:\xampp\htdocs\Yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\GatWebTest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/gatwebtest/index.php?r=index
---
2016/06/13 08:57:43 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "index".' in C:\xampp\htdocs\Yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\Yii\framework\web\CWebApplication.php(141): CWebApplication->runController('index')
#1 C:\xampp\htdocs\Yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\GatWebTest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/gatwebtest/index.php?r=index
---
2016/06/13 09:03:33 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "index".' in C:\xampp\htdocs\Yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\Yii\framework\web\CWebApplication.php(141): CWebApplication->runController('index')
#1 C:\xampp\htdocs\Yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\GatWebTest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/gatwebtest/index.php?r=index
---
2016/06/13 09:04:41 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "index".' in C:\xampp\htdocs\Yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\Yii\framework\web\CWebApplication.php(141): CWebApplication->runController('index')
#1 C:\xampp\htdocs\Yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\GatWebTest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/gatwebtest/index.php?r=index
---
2016/06/13 09:04:44 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "index".' in C:\xampp\htdocs\Yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\Yii\framework\web\CWebApplication.php(141): CWebApplication->runController('index')
#1 C:\xampp\htdocs\Yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#2 C:\xampp\htdocs\GatWebTest\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/gatwebtest/index.php?r=index
---
2016/06/13 09:42:00 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in C:\xampp\htdocs\Yii\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\Yii\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 C:\xampp\htdocs\Yii\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\Yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\Yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\Yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\Yii\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\Yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\Yii\framework\web\CWebApplication.php(282): CController->run('admin')
#8 C:\xampp\htdocs\Yii\framework\web\CWebApplication.php(141): CWebApplication->runController('account/admin')
#9 C:\xampp\htdocs\Yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#10 C:\xampp\htdocs\GatWebTest\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/gatwebtest/index.php?r=account/admin
HTTP_REFERER=http://localhost:81/gatwebtest/index.php?r=account/create
---
2016/06/13 14:27:01 [error] [exception.CException] exception 'CException' with message 'CActiveForm and its behaviors do not have a method or closure named "field".' in C:\xampp\htdocs\Yii\framework\base\CComponent.php:266
Stack trace:
#0 C:\xampp\htdocs\GatWebTest\protected\views\account\_form.php(45): CComponent->__call('field', Array)
#1 C:\xampp\htdocs\GatWebTest\protected\views\account\_form.php(45): CActiveForm->field(Object(Account), 'file')
#2 C:\xampp\htdocs\Yii\framework\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\Yii\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#4 C:\xampp\htdocs\Yii\framework\web\CController.php(869): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#5 C:\xampp\htdocs\GatWebTest\protected\views\account\create.php(18): CController->renderPartial('_form', Array)
#6 C:\xampp\htdocs\Yii\framework\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#7 C:\xampp\htdocs\Yii\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#8 C:\xampp\htdocs\Yii\framework\web\CController.php(869): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#9 C:\xampp\htdocs\Yii\framework\web\CController.php(782): CController->renderPartial('create', Array, true)
#10 C:\xampp\htdocs\GatWebTest\protected\controllers\AccountController.php(79): CController->render('create', Array)
#11 C:\xampp\htdocs\Yii\framework\web\actions\CInlineAction.php(49): AccountController->actionCreate()
#12 C:\xampp\htdocs\Yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#13 C:\xampp\htdocs\Yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#14 C:\xampp\htdocs\Yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#15 C:\xampp\htdocs\Yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#16 C:\xampp\htdocs\Yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#17 C:\xampp\htdocs\Yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#18 C:\xampp\htdocs\Yii\framework\web\CController.php(291): CFilterChain->run()
#19 C:\xampp\htdocs\Yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#20 C:\xampp\htdocs\Yii\framework\web\CWebApplication.php(282): CController->run('create')
#21 C:\xampp\htdocs\Yii\framework\web\CWebApplication.php(141): CWebApplication->runController('account/create')
#22 C:\xampp\htdocs\Yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#23 C:\xampp\htdocs\GatWebTest\index.php(13): CApplication->run()
#24 {main}
REQUEST_URI=/gatwebtest/index.php?r=account/create
HTTP_REFERER=http://localhost:81/gatwebtest/index.php?r=account/index
---
2016/06/13 14:28:28 [error] [exception.CException] exception 'CException' with message 'CActiveForm and its behaviors do not have a method or closure named "field".' in C:\xampp\htdocs\Yii\framework\base\CComponent.php:266
Stack trace:
#0 C:\xampp\htdocs\GatWebTest\protected\views\account\_form.php(44): CComponent->__call('field', Array)
#1 C:\xampp\htdocs\GatWebTest\protected\views\account\_form.php(44): CActiveForm->field(Object(Account), 'batch')
#2 C:\xampp\htdocs\Yii\framework\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\Yii\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#4 C:\xampp\htdocs\Yii\framework\web\CController.php(869): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#5 C:\xampp\htdocs\GatWebTest\protected\views\account\create.php(18): CController->renderPartial('_form', Array)
#6 C:\xampp\htdocs\Yii\framework\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#7 C:\xampp\htdocs\Yii\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#8 C:\xampp\htdocs\Yii\framework\web\CController.php(869): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#9 C:\xampp\htdocs\Yii\framework\web\CController.php(782): CController->renderPartial('create', Array, true)
#10 C:\xampp\htdocs\GatWebTest\protected\controllers\AccountController.php(79): CController->render('create', Array)
#11 C:\xampp\htdocs\Yii\framework\web\actions\CInlineAction.php(49): AccountController->actionCreate()
#12 C:\xampp\htdocs\Yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#13 C:\xampp\htdocs\Yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#14 C:\xampp\htdocs\Yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#15 C:\xampp\htdocs\Yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#16 C:\xampp\htdocs\Yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#17 C:\xampp\htdocs\Yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#18 C:\xampp\htdocs\Yii\framework\web\CController.php(291): CFilterChain->run()
#19 C:\xampp\htdocs\Yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#20 C:\xampp\htdocs\Yii\framework\web\CWebApplication.php(282): CController->run('create')
#21 C:\xampp\htdocs\Yii\framework\web\CWebApplication.php(141): CWebApplication->runController('account/create')
#22 C:\xampp\htdocs\Yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#23 C:\xampp\htdocs\GatWebTest\index.php(13): CApplication->run()
#24 {main}
REQUEST_URI=/gatwebtest/index.php?r=account/create
HTTP_REFERER=http://localhost:81/gatwebtest/index.php?r=account/index
---
2016/06/13 14:50:10 [error] [exception.CException] exception 'CException' with message 'CActiveForm and its behaviors do not have a method or closure named "field".' in C:\xampp\htdocs\Yii\framework\base\CComponent.php:266
Stack trace:
#0 C:\xampp\htdocs\GatWebTest\protected\views\account\_form.php(44): CComponent->__call('field', Array)
#1 C:\xampp\htdocs\GatWebTest\protected\views\account\_form.php(44): CActiveForm->field(Object(Account), 'batch')
#2 C:\xampp\htdocs\Yii\framework\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\Yii\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#4 C:\xampp\htdocs\Yii\framework\web\CController.php(869): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#5 C:\xampp\htdocs\GatWebTest\protected\views\account\create.php(18): CController->renderPartial('_form', Array)
#6 C:\xampp\htdocs\Yii\framework\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#7 C:\xampp\htdocs\Yii\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#8 C:\xampp\htdocs\Yii\framework\web\CController.php(869): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#9 C:\xampp\htdocs\Yii\framework\web\CController.php(782): CController->renderPartial('create', Array, true)
#10 C:\xampp\htdocs\GatWebTest\protected\controllers\AccountController.php(79): CController->render('create', Array)
#11 C:\xampp\htdocs\Yii\framework\web\actions\CInlineAction.php(49): AccountController->actionCreate()
#12 C:\xampp\htdocs\Yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#13 C:\xampp\htdocs\Yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#14 C:\xampp\htdocs\Yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#15 C:\xampp\htdocs\Yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#16 C:\xampp\htdocs\Yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#17 C:\xampp\htdocs\Yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#18 C:\xampp\htdocs\Yii\framework\web\CController.php(291): CFilterChain->run()
#19 C:\xampp\htdocs\Yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#20 C:\xampp\htdocs\Yii\framework\web\CWebApplication.php(282): CController->run('create')
#21 C:\xampp\htdocs\Yii\framework\web\CWebApplication.php(141): CWebApplication->runController('account/create')
#22 C:\xampp\htdocs\Yii\framework\base\CApplication.php(184): CWebApplication->processRequest()
#23 C:\xampp\htdocs\GatWebTest\index.php(13): CApplication->run()
#24 {main}
REQUEST_URI=/gatwebtest/index.php?r=account/create
HTTP_REFERER=http://localhost:81/gatwebtest/index.php?r=account/index
---
2017/08/27 10:10:19 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1049] Unknown database 'license'' in C:\xampp\htdocs\GatWebTest\protected\framework\db\CDbConnection.php:382
Stack trace:
#0 C:\xampp\htdocs\GatWebTest\protected\framework\db\CDbConnection.php(330): CDbConnection->open()
#1 C:\xampp\htdocs\GatWebTest\protected\framework\db\CDbConnection.php(308): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\GatWebTest\protected\framework\base\CModule.php(387): CDbConnection->init()
#3 C:\xampp\htdocs\GatWebTest\protected\framework\base\CApplication.php(450): CModule->getComponent('db')
#4 C:\xampp\htdocs\GatWebTest\protected\framework\db\ar\CActiveRecord.php(634): CApplication->getDb()
#5 C:\xampp\htdocs\GatWebTest\protected\framework\db\ar\CActiveRecord.php(667): CActiveRecord->getDbConnection()
#6 C:\xampp\htdocs\GatWebTest\protected\framework\db\ar\CActiveRecord.php(1595): CActiveRecord->getCommandBuilder()
#7 C:\xampp\htdocs\GatWebTest\protected\framework\web\CActiveDataProvider.php(228): CActiveRecord->count(Object(CDbCriteria))
#8 C:\xampp\htdocs\GatWebTest\protected\framework\web\CDataProvider.php(224): CActiveDataProvider->calculateTotalItemCount()
#9 C:\xampp\htdocs\GatWebTest\protected\framework\web\CActiveDataProvider.php(178): CDataProvider->getTotalItemCount()
#10 C:\xampp\htdocs\GatWebTest\protected\framework\web\CDataProvider.php(168): CActiveDataProvider->fetchData()
#11 C:\xampp\htdocs\GatWebTest\protected\framework\zii\widgets\CBaseListView.php(111): CDataProvider->getData()
#12 C:\xampp\htdocs\GatWebTest\protected\framework\zii\widgets\CListView.php(211): CBaseListView->init()
#13 C:\xampp\htdocs\GatWebTest\protected\framework\web\CBaseController.php(147): CListView->init()
#14 C:\xampp\htdocs\GatWebTest\protected\framework\web\CBaseController.php(172): CBaseController->createWidget('zii.widgets.CLi...', Array)
#15 C:\xampp\htdocs\GatWebTest\protected\views\account\index.php(20): CBaseController->widget('zii.widgets.CLi...', Array)
#16 C:\xampp\htdocs\GatWebTest\protected\framework\web\CBaseController.php(126): require('C:\xampp\htdocs...')
#17 C:\xampp\htdocs\GatWebTest\protected\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\xampp\htdocs...', Array, true)
#18 C:\xampp\htdocs\GatWebTest\protected\framework\web\CController.php(869): CBaseController->renderFile('C:\xampp\htdocs...', Array, true)
#19 C:\xampp\htdocs\GatWebTest\protected\framework\web\CController.php(782): CController->renderPartial('index', Array, true)
#20 C:\xampp\htdocs\GatWebTest\protected\controllers\AccountController.php(128): CController->render('index', Array)
#21 C:\xampp\htdocs\GatWebTest\protected\framework\web\actions\CInlineAction.php(49): AccountController->actionIndex()
#22 C:\xampp\htdocs\GatWebTest\protected\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#23 C:\xampp\htdocs\GatWebTest\protected\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#24 C:\xampp\htdocs\GatWebTest\protected\framework\web\filters\CFilter.php(40): CFilterChain->run()
#25 C:\xampp\htdocs\GatWebTest\protected\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#26 C:\xampp\htdocs\GatWebTest\protected\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#27 C:\xampp\htdocs\GatWebTest\protected\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#28 C:\xampp\htdocs\GatWebTest\protected\framework\web\CController.php(291): CFilterChain->run()
#29 C:\xampp\htdocs\GatWebTest\protected\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#30 C:\xampp\htdocs\GatWebTest\protected\framework\web\CWebApplication.php(283): CController->run('index')
#31 C:\xampp\htdocs\GatWebTest\protected\framework\web\CWebApplication.php(140): CWebApplication->runController('account/index')
#32 C:\xampp\htdocs\GatWebTest\protected\framework\base\CApplication.php(180): CWebApplication->processRequest()
#33 C:\xampp\htdocs\GatWebTest\index.php(13): CApplication->run()
#34 {main}
REQUEST_URI=/GatWebTest/index.php?r=account/index
HTTP_REFERER=http://localhost/GatWebTest/index.php?r=site/contact
---
2017/08/27 10:12:27 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1049] Unknown database 'enews'' in C:\xampp\htdocs\GatWebTest\protected\framework\db\CDbConnection.php:382
Stack trace:
#0 C:\xampp\htdocs\GatWebTest\protected\framework\db\CDbConnection.php(330): CDbConnection->open()
#1 C:\xampp\htdocs\GatWebTest\protected\framework\db\CDbConnection.php(308): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\GatWebTest\protected\framework\base\CModule.php(387): CDbConnection->init()
#3 C:\xampp\htdocs\GatWebTest\protected\framework\base\CApplication.php(450): CModule->getComponent('db')
#4 C:\xampp\htdocs\GatWebTest\protected\framework\db\ar\CActiveRecord.php(634): CApplication->getDb()
#5 C:\xampp\htdocs\GatWebTest\protected\framework\db\ar\CActiveRecord.php(667): CActiveRecord->getDbConnection()
#6 C:\xampp\htdocs\GatWebTest\protected\framework\db\ar\CActiveRecord.php(1595): CActiveRecord->getCommandBuilder()
#7 C:\xampp\htdocs\GatWebTest\protected\framework\web\CActiveDataProvider.php(228): CActiveRecord->count(Object(CDbCriteria))
#8 C:\xampp\htdocs\GatWebTest\protected\framework\web\CDataProvider.php(224): CActiveDataProvider->calculateTotalItemCount()
#9 C:\xampp\htdocs\GatWebTest\protected\framework\web\CActiveDataProvider.php(178): CDataProvider->getTotalItemCount()
#10 C:\xampp\htdocs\GatWebTest\protected\framework\web\CDataProvider.php(168): CActiveDataProvider->fetchData()
#11 C:\xampp\htdocs\GatWebTest\protected\framework\zii\widgets\CBaseListView.php(111): CDataProvider->getData()
#12 C:\xampp\htdocs\GatWebTest\protected\framework\zii\widgets\CListView.php(211): CBaseListView->init()
#13 C:\xampp\htdocs\GatWebTest\protected\framework\web\CBaseController.php(147): CListView->init()
#14 C:\xampp\htdocs\GatWebTest\protected\framework\web\CBaseController.php(172): CBaseController->createWidget('zii.widgets.CLi...', Array)
#15 C:\xampp\htdocs\GatWebTest\protected\views\account\index.php(20): CBaseController->widget('zii.widgets.CLi...', Array)
#16 C:\xampp\htdocs\GatWebTest\protected\framework\web\CBaseController.php(126): require('C:\xampp\htdocs...')
#17 C:\xampp\htdocs\GatWebTest\protected\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\xampp\htdocs...', Array, true)
#18 C:\xampp\htdocs\GatWebTest\protected\framework\web\CController.php(869): CBaseController->renderFile('C:\xampp\htdocs...', Array, true)
#19 C:\xampp\htdocs\GatWebTest\protected\framework\web\CController.php(782): CController->renderPartial('index', Array, true)
#20 C:\xampp\htdocs\GatWebTest\protected\controllers\AccountController.php(128): CController->render('index', Array)
#21 C:\xampp\htdocs\GatWebTest\protected\framework\web\actions\CInlineAction.php(49): AccountController->actionIndex()
#22 C:\xampp\htdocs\GatWebTest\protected\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#23 C:\xampp\htdocs\GatWebTest\protected\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#24 C:\xampp\htdocs\GatWebTest\protected\framework\web\filters\CFilter.php(40): CFilterChain->run()
#25 C:\xampp\htdocs\GatWebTest\protected\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#26 C:\xampp\htdocs\GatWebTest\protected\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#27 C:\xampp\htdocs\GatWebTest\protected\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#28 C:\xampp\htdocs\GatWebTest\protected\framework\web\CController.php(291): CFilterChain->run()
#29 C:\xampp\htdocs\GatWebTest\protected\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#30 C:\xampp\htdocs\GatWebTest\protected\framework\web\CWebApplication.php(283): CController->run('index')
#31 C:\xampp\htdocs\GatWebTest\protected\framework\web\CWebApplication.php(140): CWebApplication->runController('account/index')
#32 C:\xampp\htdocs\GatWebTest\protected\framework\base\CApplication.php(180): CWebApplication->processRequest()
#33 C:\xampp\htdocs\GatWebTest\index.php(13): CApplication->run()
#34 {main}
REQUEST_URI=/GatWebTest/index.php?r=account/index
HTTP_REFERER=http://localhost/GatWebTest/index.php?r=site/contact
---
2017/08/27 10:12:57 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'enews_v1.account' doesn't exist. The SQL statement executed was: SHOW FULL COLUMNS FROM `account`.
in C:\xampp\htdocs\GatWebTest\protected\views\account\index.php (20)
in C:\xampp\htdocs\GatWebTest\protected\controllers\AccountController.php (128)
in C:\xampp\htdocs\GatWebTest\index.php (13)
2017/08/27 10:12:57 [error] [exception.CDbException] exception 'CDbException' with message 'The table "account" for active record class "Account" cannot be found in the database.' in C:\xampp\htdocs\GatWebTest\protected\framework\db\ar\CActiveRecord.php:2362
Stack trace:
#0 C:\xampp\htdocs\GatWebTest\protected\framework\db\ar\CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(Account))
#1 C:\xampp\htdocs\GatWebTest\protected\framework\db\ar\CActiveRecord.php(658): CActiveRecord->getMetaData()
#2 C:\xampp\htdocs\GatWebTest\protected\framework\db\ar\CActiveRecord.php(1601): CActiveRecord->getTableSchema()
#3 C:\xampp\htdocs\GatWebTest\protected\framework\web\CActiveDataProvider.php(228): CActiveRecord->count(Object(CDbCriteria))
#4 C:\xampp\htdocs\GatWebTest\protected\framework\web\CDataProvider.php(224): CActiveDataProvider->calculateTotalItemCount()
#5 C:\xampp\htdocs\GatWebTest\protected\framework\web\CActiveDataProvider.php(178): CDataProvider->getTotalItemCount()
#6 C:\xampp\htdocs\GatWebTest\protected\framework\web\CDataProvider.php(168): CActiveDataProvider->fetchData()
#7 C:\xampp\htdocs\GatWebTest\protected\framework\zii\widgets\CBaseListView.php(111): CDataProvider->getData()
#8 C:\xampp\htdocs\GatWebTest\protected\framework\zii\widgets\CListView.php(211): CBaseListView->init()
#9 C:\xampp\htdocs\GatWebTest\protected\framework\web\CBaseController.php(147): CListView->init()
#10 C:\xampp\htdocs\GatWebTest\protected\framework\web\CBaseController.php(172): CBaseController->createWidget('zii.widgets.CLi...', Array)
#11 C:\xampp\htdocs\GatWebTest\protected\views\account\index.php(20): CBaseController->widget('zii.widgets.CLi...', Array)
#12 C:\xampp\htdocs\GatWebTest\protected\framework\web\CBaseController.php(126): require('C:\xampp\htdocs...')
#13 C:\xampp\htdocs\GatWebTest\protected\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\xampp\htdocs...', Array, true)
#14 C:\xampp\htdocs\GatWebTest\protected\framework\web\CController.php(869): CBaseController->renderFile('C:\xampp\htdocs...', Array, true)
#15 C:\xampp\htdocs\GatWebTest\protected\framework\web\CController.php(782): CController->renderPartial('index', Array, true)
#16 C:\xampp\htdocs\GatWebTest\protected\controllers\AccountController.php(128): CController->render('index', Array)
#17 C:\xampp\htdocs\GatWebTest\protected\framework\web\actions\CInlineAction.php(49): AccountController->actionIndex()
#18 C:\xampp\htdocs\GatWebTest\protected\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#19 C:\xampp\htdocs\GatWebTest\protected\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#20 C:\xampp\htdocs\GatWebTest\protected\framework\web\filters\CFilter.php(40): CFilterChain->run()
#21 C:\xampp\htdocs\GatWebTest\protected\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#22 C:\xampp\htdocs\GatWebTest\protected\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#23 C:\xampp\htdocs\GatWebTest\protected\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#24 C:\xampp\htdocs\GatWebTest\protected\framework\web\CController.php(291): CFilterChain->run()
#25 C:\xampp\htdocs\GatWebTest\protected\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#26 C:\xampp\htdocs\GatWebTest\protected\framework\web\CWebApplication.php(283): CController->run('index')
#27 C:\xampp\htdocs\GatWebTest\protected\framework\web\CWebApplication.php(140): CWebApplication->runController('account/index')
#28 C:\xampp\htdocs\GatWebTest\protected\framework\base\CApplication.php(180): CWebApplication->processRequest()
#29 C:\xampp\htdocs\GatWebTest\index.php(13): CApplication->run()
#30 {main}
REQUEST_URI=/GatWebTest/index.php?r=account/index
HTTP_REFERER=http://localhost/GatWebTest/index.php?r=site/contact
---
2017/08/27 11:15:17 [error] [php] include(Account.php): failed to open stream: No such file or directory (C:\xampp\htdocs\Autologs\protected\framework\YiiBase.php:427)
Stack trace:
#0 C:\xampp\htdocs\Autologs\protected\components\UserIdentity.php(15): spl_autoload_call()
#1 C:\xampp\htdocs\Autologs\protected\models\LoginForm.php(52): UserIdentity->authenticate()
#2 C:\xampp\htdocs\Autologs\protected\framework\validators\CInlineValidator.php(42): LoginForm->authenticate()
#3 C:\xampp\htdocs\Autologs\protected\framework\validators\CValidator.php(213): CInlineValidator->validateAttribute()
#4 C:\xampp\htdocs\Autologs\protected\framework\base\CModel.php(159): CInlineValidator->validate()
#5 C:\xampp\htdocs\Autologs\protected\controllers\SiteController.php(118): LoginForm->validate()
#6 C:\xampp\htdocs\Autologs\protected\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#7 C:\xampp\htdocs\Autologs\protected\framework\web\CController.php(308): CInlineAction->runWithParams()
#8 C:\xampp\htdocs\Autologs\protected\framework\web\CController.php(286): SiteController->runAction()
#9 C:\xampp\htdocs\Autologs\protected\framework\web\CController.php(265): SiteController->runActionWithFilters()
#10 C:\xampp\htdocs\Autologs\protected\framework\web\CWebApplication.php(283): SiteController->run()
#11 C:\xampp\htdocs\Autologs\protected\framework\web\CWebApplication.php(140): CWebApplication->runController()
#12 C:\xampp\htdocs\Autologs\protected\framework\base\CApplication.php(180): CWebApplication->processRequest()
#13 C:\xampp\htdocs\Autologs\index.php(13): CWebApplication->run()
REQUEST_URI=/Autologs/index.php?r=site/login
in C:\xampp\htdocs\Autologs\protected\components\UserIdentity.php (15)
in C:\xampp\htdocs\Autologs\protected\models\LoginForm.php (52)
in C:\xampp\htdocs\Autologs\protected\controllers\SiteController.php (118)
2017/08/27 11:16:00 [error] [exception.CDbException] exception 'CDbException' with message 'Table "tbusers" does not have a column named "password".' in C:\xampp\htdocs\Autologs\protected\framework\db\schema\CDbCommandBuilder.php:694
Stack trace:
#0 C:\xampp\htdocs\Autologs\protected\framework\db\ar\CActiveRecord.php(1518): CDbCommandBuilder->createColumnCriteria(Object(CMysqlTableSchema), Array, '', Array, '`t`.')
#1 C:\xampp\htdocs\Autologs\protected\components\UserIdentity.php(16): CActiveRecord->findByAttributes(Array)
#2 C:\xampp\htdocs\Autologs\protected\models\LoginForm.php(52): UserIdentity->authenticate()
#3 C:\xampp\htdocs\Autologs\protected\framework\validators\CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#4 C:\xampp\htdocs\Autologs\protected\framework\validators\CValidator.php(213): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#5 C:\xampp\htdocs\Autologs\protected\framework\base\CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#6 C:\xampp\htdocs\Autologs\protected\controllers\SiteController.php(118): CModel->validate()
#7 C:\xampp\htdocs\Autologs\protected\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#8 C:\xampp\htdocs\Autologs\protected\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#9 C:\xampp\htdocs\Autologs\protected\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#10 C:\xampp\htdocs\Autologs\protected\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 C:\xampp\htdocs\Autologs\protected\framework\web\CWebApplication.php(283): CController->run('login')
#12 C:\xampp\htdocs\Autologs\protected\framework\web\CWebApplication.php(140): CWebApplication->runController('site/login')
#13 C:\xampp\htdocs\Autologs\protected\framework\base\CApplication.php(180): CWebApplication->processRequest()
#14 C:\xampp\htdocs\Autologs\index.php(13): CApplication->run()
#15 {main}
REQUEST_URI=/Autologs/index.php?r=site/login
HTTP_REFERER=http://localhost/Autologs/index.php?r=site/login
---
2017/08/27 11:16:40 [error] [exception.CException] exception 'CException' with message 'Property "Users.password" is not defined.' in C:\xampp\htdocs\Autologs\protected\framework\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\Autologs\protected\framework\db\ar\CActiveRecord.php(145): CComponent->__get('password')
#1 C:\xampp\htdocs\Autologs\protected\components\UserIdentity.php(20): CActiveRecord->__get('password')
#2 C:\xampp\htdocs\Autologs\protected\models\LoginForm.php(52): UserIdentity->authenticate()
#3 C:\xampp\htdocs\Autologs\protected\framework\validators\CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#4 C:\xampp\htdocs\Autologs\protected\framework\validators\CValidator.php(213): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#5 C:\xampp\htdocs\Autologs\protected\framework\base\CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#6 C:\xampp\htdocs\Autologs\protected\controllers\SiteController.php(118): CModel->validate()
#7 C:\xampp\htdocs\Autologs\protected\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#8 C:\xampp\htdocs\Autologs\protected\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#9 C:\xampp\htdocs\Autologs\protected\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#10 C:\xampp\htdocs\Autologs\protected\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 C:\xampp\htdocs\Autologs\protected\framework\web\CWebApplication.php(283): CController->run('login')
#12 C:\xampp\htdocs\Autologs\protected\framework\web\CWebApplication.php(140): CWebApplication->runController('site/login')
#13 C:\xampp\htdocs\Autologs\protected\framework\base\CApplication.php(180): CWebApplication->processRequest()
#14 C:\xampp\htdocs\Autologs\index.php(13): CApplication->run()
#15 {main}
REQUEST_URI=/Autologs/index.php?r=site/login
HTTP_REFERER=http://localhost/Autologs/index.php?r=site/login
---
2017/08/27 11:18:07 [error] [exception.CException] exception 'CException' with message 'Property "Users.password" is not defined.' in C:\xampp\htdocs\Autologs\protected\framework\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\Autologs\protected\framework\db\ar\CActiveRecord.php(145): CComponent->__get('password')
#1 C:\xampp\htdocs\Autologs\protected\components\UserIdentity.php(20): CActiveRecord->__get('password')
#2 C:\xampp\htdocs\Autologs\protected\models\LoginForm.php(52): UserIdentity->authenticate()
#3 C:\xampp\htdocs\Autologs\protected\framework\validators\CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#4 C:\xampp\htdocs\Autologs\protected\framework\validators\CValidator.php(213): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#5 C:\xampp\htdocs\Autologs\protected\framework\base\CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#6 C:\xampp\htdocs\Autologs\protected\controllers\SiteController.php(118): CModel->validate()
#7 C:\xampp\htdocs\Autologs\protected\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#8 C:\xampp\htdocs\Autologs\protected\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#9 C:\xampp\htdocs\Autologs\protected\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#10 C:\xampp\htdocs\Autologs\protected\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 C:\xampp\htdocs\Autologs\protected\framework\web\CWebApplication.php(283): CController->run('login')
#12 C:\xampp\htdocs\Autologs\protected\framework\web\CWebApplication.php(140): CWebApplication->runController('site/login')
#13 C:\xampp\htdocs\Autologs\protected\framework\base\CApplication.php(180): CWebApplication->processRequest()
#14 C:\xampp\htdocs\Autologs\index.php(13): CApplication->run()
#15 {main}
REQUEST_URI=/Autologs/index.php?r=site/login
HTTP_REFERER=http://localhost/Autologs/index.php?r=site/login
---
2017/08/27 11:18:52 [error] [exception.CException] exception 'CException' with message 'Property "UserIdentity.userpassword" is not defined.' in C:\xampp\htdocs\Autologs\protected\framework\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\Autologs\protected\components\UserIdentity.php(16): CComponent->__get('userpassword')
#1 C:\xampp\htdocs\Autologs\protected\models\LoginForm.php(52): UserIdentity->authenticate()
#2 C:\xampp\htdocs\Autologs\protected\framework\validators\CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#3 C:\xampp\htdocs\Autologs\protected\framework\validators\CValidator.php(213): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#4 C:\xampp\htdocs\Autologs\protected\framework\base\CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#5 C:\xampp\htdocs\Autologs\protected\controllers\SiteController.php(118): CModel->validate()
#6 C:\xampp\htdocs\Autologs\protected\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#7 C:\xampp\htdocs\Autologs\protected\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#8 C:\xampp\htdocs\Autologs\protected\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#9 C:\xampp\htdocs\Autologs\protected\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#10 C:\xampp\htdocs\Autologs\protected\framework\web\CWebApplication.php(283): CController->run('login')
#11 C:\xampp\htdocs\Autologs\protected\framework\web\CWebApplication.php(140): CWebApplication->runController('site/login')
#12 C:\xampp\htdocs\Autologs\protected\framework\base\CApplication.php(180): CWebApplication->processRequest()
#13 C:\xampp\htdocs\Autologs\index.php(13): CApplication->run()
#14 {main}
REQUEST_URI=/Autologs/index.php?r=site/login
HTTP_REFERER=http://localhost/Autologs/index.php?r=site/login
---
2017/08/27 11:19:25 [error] [exception.CException] exception 'CException' with message 'Property "Users.ac_id" is not defined.' in C:\xampp\htdocs\Autologs\protected\framework\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\Autologs\protected\framework\db\ar\CActiveRecord.php(145): CComponent->__get('ac_id')
#1 C:\xampp\htdocs\Autologs\protected\components\UserIdentity.php(24): CActiveRecord->__get('ac_id')
#2 C:\xampp\htdocs\Autologs\protected\models\LoginForm.php(52): UserIdentity->authenticate()
#3 C:\xampp\htdocs\Autologs\protected\framework\validators\CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#4 C:\xampp\htdocs\Autologs\protected\framework\validators\CValidator.php(213): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#5 C:\xampp\htdocs\Autologs\protected\framework\base\CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#6 C:\xampp\htdocs\Autologs\protected\controllers\SiteController.php(118): CModel->validate()
#7 C:\xampp\htdocs\Autologs\protected\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#8 C:\xampp\htdocs\Autologs\protected\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#9 C:\xampp\htdocs\Autologs\protected\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#10 C:\xampp\htdocs\Autologs\protected\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 C:\xampp\htdocs\Autologs\protected\framework\web\CWebApplication.php(283): CController->run('login')
#12 C:\xampp\htdocs\Autologs\protected\framework\web\CWebApplication.php(140): CWebApplication->runController('site/login')
#13 C:\xampp\htdocs\Autologs\protected\framework\base\CApplication.php(180): CWebApplication->processRequest()
#14 C:\xampp\htdocs\Autologs\index.php(13): CApplication->run()
#15 {main}
REQUEST_URI=/Autologs/index.php?r=site/login
HTTP_REFERER=http://localhost/Autologs/index.php?r=site/login
---
2017/08/27 11:25:33 [error] [php] include(Account.php): failed to open stream: No such file or directory (C:\xampp\htdocs\Autologs\protected\framework\YiiBase.php:427)
Stack trace:
#0 C:\xampp\htdocs\Autologs\protected\framework\db\ar\CActiveRecord.php(395): spl_autoload_call()
#1 C:\xampp\htdocs\Autologs\protected\framework\web\CActiveDataProvider.php(165): model()
#2 C:\xampp\htdocs\Autologs\protected\framework\web\CActiveDataProvider.php(87): CActiveDataProvider->getModel()
#3 C:\xampp\htdocs\Autologs\protected\controllers\AccountController.php(125): CActiveDataProvider->__construct()
#4 C:\xampp\htdocs\Autologs\protected\framework\web\actions\CInlineAction.php(49): AccountController->actionIndex()
#5 C:\xampp\htdocs\Autologs\protected\framework\web\CController.php(308): CInlineAction->runWithParams()
#6 C:\xampp\htdocs\Autologs\protected\framework\web\filters\CFilterChain.php(133): AccountController->runAction()
#7 C:\xampp\htdocs\Autologs\protected\framework\web\filters\CFilter.php(40): CFilterChain->run()
#8 C:\xampp\htdocs\Autologs\protected\framework\web\CController.php(1145): CAccessControlFilter->filter()
#9 C:\xampp\htdocs\Autologs\protected\framework\web\filters\CInlineFilter.php(58): AccountController->filterAccessControl()
#10 C:\xampp\htdocs\Autologs\protected\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#11 C:\xampp\htdocs\Autologs\protected\framework\web\CController.php(291): CFilterChain->run()
#12 C:\xampp\htdocs\Autologs\protected\framework\web\CController.php(265): AccountController->runActionWithFilters()
#13 C:\xampp\htdocs\Autologs\protected\framework\web\CWebApplication.php(283): AccountController->run()
#14 C:\xampp\htdocs\Autologs\protected\framework\web\CWebApplication.php(140): CWebApplication->runController()
#15 C:\xampp\htdocs\Autologs\protected\framework\base\CApplication.php(180): CWebApplication->processRequest()
#16 C:\xampp\htdocs\Autologs\index.php(13): CWebApplication->run()
REQUEST_URI=/Autologs/index.php?r=account/index
in C:\xampp\htdocs\Autologs\protected\controllers\AccountController.php (125)
in C:\xampp\htdocs\Autologs\index.php (13)
2017/08/27 11:28:49 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "account/index".' in C:\xampp\htdocs\Autologs\protected\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\Autologs\protected\framework\web\CWebApplication.php(140): CWebApplication->runController('account/index')
#1 C:\xampp\htdocs\Autologs\protected\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\Autologs\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/Autologs/index.php?r=account/index
HTTP_REFERER=http://localhost/Autologs/index.php?r=site/contact
---
2017/08/27 11:29:03 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "account/index".' in C:\xampp\htdocs\Autologs\protected\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\Autologs\protected\framework\web\CWebApplication.php(140): CWebApplication->runController('account/index')
#1 C:\xampp\htdocs\Autologs\protected\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\Autologs\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/Autologs/index.php?r=account/index
HTTP_REFERER=http://localhost/Autologs/index.php?r=site/index
---
2017/08/27 11:33:21 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "account/index".' in C:\xampp\htdocs\Autologs\protected\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\Autologs\protected\framework\web\CWebApplication.php(140): CWebApplication->runController('account/index')
#1 C:\xampp\htdocs\Autologs\protected\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\Autologs\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/Autologs/index.php?r=account/index
HTTP_REFERER=http://localhost/Autologs/index.php?r=account/index
---
2017/08/27 11:33:28 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "account/index".' in C:\xampp\htdocs\Autologs\protected\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\Autologs\protected\framework\web\CWebApplication.php(140): CWebApplication->runController('account/index')
#1 C:\xampp\htdocs\Autologs\protected\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\xampp\htdocs\Autologs\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/Autologs/index.php?r=account/index
HTTP_REFERER=http://localhost/Autologs/index.php?r=account/index
---
2017/08/27 11:39:29 [error] [exception.CException] exception 'CException' with message 'Property "Users.ac_id" is not defined.' in C:\xampp\htdocs\Autologs\protected\framework\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\Autologs\protected\framework\db\ar\CActiveRecord.php(145): CComponent->__get('ac_id')
#1 C:\xampp\htdocs\Autologs\protected\views\Users\_view.php(7): CActiveRecord->__get('ac_id')
#2 C:\xampp\htdocs\Autologs\protected\framework\web\CBaseController.php(130): require('C:\xampp\htdocs...')
#3 C:\xampp\htdocs\Autologs\protected\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\xampp\htdocs...', Array, false)
#4 C:\xampp\htdocs\Autologs\protected\framework\zii\widgets\CListView.php(291): CBaseController->renderFile('C:\xampp\htdocs...', Array)
#5 C:\xampp\htdocs\Autologs\protected\framework\zii\widgets\CBaseListView.php(167): CListView->renderItems()
#6 [internal function]: CBaseListView->renderSection(Array)
#7 C:\xampp\htdocs\Autologs\protected\framework\zii\widgets\CBaseListView.php(150): preg_replace_callback('/{(\w+)}/', Array, '{summary}?{sort...')
#8 C:\xampp\htdocs\Autologs\protected\framework\zii\widgets\CBaseListView.php(135): CBaseListView->renderContent()
#9 C:\xampp\htdocs\Autologs\protected\framework\web\CBaseController.php(173): CBaseListView->run()
#10 C:\xampp\htdocs\Autologs\protected\views\Users\index.php(20): CBaseController->widget('zii.widgets.CLi...', Array)
#11 C:\xampp\htdocs\Autologs\protected\framework\web\CBaseController.php(126): require('C:\xampp\htdocs...')
#12 C:\xampp\htdocs\Autologs\protected\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\xampp\htdocs...', Array, true)
#13 C:\xampp\htdocs\Autologs\protected\framework\web\CController.php(869): CBaseController->renderFile('C:\xampp\htdocs...', Array, true)
#14 C:\xampp\htdocs\Autologs\protected\framework\web\CController.php(782): CController->renderPartial('index', Array, true)
#15 C:\xampp\htdocs\Autologs\protected\controllers\UsersController.php(128): CController->render('index', Array)
#16 C:\xampp\htdocs\Autologs\protected\framework\web\actions\CInlineAction.php(49): UsersController->actionIndex()
#17 C:\xampp\htdocs\Autologs\protected\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#18 C:\xampp\htdocs\Autologs\protected\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#19 C:\xampp\htdocs\Autologs\protected\framework\web\filters\CFilter.php(40): CFilterChain->run()
#20 C:\xampp\htdocs\Autologs\protected\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#21 C:\xampp\htdocs\Autologs\protected\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#22 C:\xampp\htdocs\Autologs\protected\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#23 C:\xampp\htdocs\Autologs\protected\framework\web\CController.php(291): CFilterChain->run()
#24 C:\xampp\htdocs\Autologs\protected\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#25 C:\xampp\htdocs\Autologs\protected\framework\web\CWebApplication.php(283): CController->run('index')
#26 C:\xampp\htdocs\Autologs\protected\framework\web\CWebApplication.php(140): CWebApplication->runController('Users/index')
#27 C:\xampp\htdocs\Autologs\protected\framework\base\CApplication.php(180): CWebApplication->processRequest()
#28 C:\xampp\htdocs\Autologs\index.php(13): CApplication->run()
#29 {main}
REQUEST_URI=/Autologs/index.php?r=Users/index
HTTP_REFERER=http://localhost/Autologs/index.php?r=site/index
---
2017/08/27 11:39:49 [error] [exception.CException] exception 'CException' with message 'Property "Users.ac_id" is not defined.' in C:\xampp\htdocs\Autologs\protected\framework\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\Autologs\protected\framework\db\ar\CActiveRecord.php(145): CComponent->__get('ac_id')
#1 C:\xampp\htdocs\Autologs\protected\views\Users\_view.php(7): CActiveRecord->__get('ac_id')
#2 C:\xampp\htdocs\Autologs\protected\framework\web\CBaseController.php(130): require('C:\xampp\htdocs...')
#3 C:\xampp\htdocs\Autologs\protected\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\xampp\htdocs...', Array, false)
#4 C:\xampp\htdocs\Autologs\protected\framework\zii\widgets\CListView.php(291): CBaseController->renderFile('C:\xampp\htdocs...', Array)
#5 C:\xampp\htdocs\Autologs\protected\framework\zii\widgets\CBaseListView.php(167): CListView->renderItems()
#6 [internal function]: CBaseListView->renderSection(Array)
#7 C:\xampp\htdocs\Autologs\protected\framework\zii\widgets\CBaseListView.php(150): preg_replace_callback('/{(\w+)}/', Array, '{summary}?{sort...')
#8 C:\xampp\htdocs\Autologs\protected\framework\zii\widgets\CBaseListView.php(135): CBaseListView->renderContent()
#9 C:\xampp\htdocs\Autologs\protected\framework\web\CBaseController.php(173): CBaseListView->run()
#10 C:\xampp\htdocs\Autologs\protected\views\Users\index.php(20): CBaseController->widget('zii.widgets.CLi...', Array)
#11 C:\xampp\htdocs\Autologs\protected\framework\web\CBaseController.php(126): require('C:\xampp\htdocs...')
#12 C:\xampp\htdocs\Autologs\protected\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\xampp\htdocs...', Array, true)
#13 C:\xampp\htdocs\Autologs\protected\framework\web\CController.php(869): CBaseController->renderFile('C:\xampp\htdocs...', Array, true)
#14 C:\xampp\htdocs\Autologs\protected\framework\web\CController.php(782): CController->renderPartial('index', Array, true)
#15 C:\xampp\htdocs\Autologs\protected\controllers\UsersController.php(128): CController->render('index', Array)
#16 C:\xampp\htdocs\Autologs\protected\framework\web\actions\CInlineAction.php(49): UsersController->actionIndex()
#17 C:\xampp\htdocs\Autologs\protected\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#18 C:\xampp\htdocs\Autologs\protected\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#19 C:\xampp\htdocs\Autologs\protected\framework\web\filters\CFilter.php(40): CFilterChain->run()
#20 C:\xampp\htdocs\Autologs\protected\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#21 C:\xampp\htdocs\Autologs\protected\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#22 C:\xampp\htdocs\Autologs\protected\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#23 C:\xampp\htdocs\Autologs\protected\framework\web\CController.php(291): CFilterChain->run()
#24 C:\xampp\htdocs\Autologs\protected\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#25 C:\xampp\htdocs\Autologs\protected\framework\web\CWebApplication.php(283): CController->run('index')
#26 C:\xampp\htdocs\Autologs\protected\framework\web\CWebApplication.php(140): CWebApplication->runController('Users/index')
#27 C:\xampp\htdocs\Autologs\protected\framework\base\CApplication.php(180): CWebApplication->processRequest()
#28 C:\xampp\htdocs\Autologs\index.php(13): CApplication->run()
#29 {main}
REQUEST_URI=/Autologs/index.php?r=Users/index
HTTP_REFERER=http://localhost/Autologs/index.php?r=site/index
---
2017/08/27 11:41:53 [error] [exception.CException] exception 'CException' with message 'Property "Users.password" is not defined.' in C:\xampp\htdocs\Autologs\protected\framework\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\Autologs\protected\framework\db\ar\CActiveRecord.php(145): CComponent->__get('password')
#1 C:\xampp\htdocs\Autologs\protected\views\Users\_view.php(30): CActiveRecord->__get('password')
#2 C:\xampp\htdocs\Autologs\protected\framework\web\CBaseController.php(130): require('C:\xampp\htdocs...')
#3 C:\xampp\htdocs\Autologs\protected\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\xampp\htdocs...', Array, false)
#4 C:\xampp\htdocs\Autologs\protected\framework\zii\widgets\CListView.php(291): CBaseController->renderFile('C:\xampp\htdocs...', Array)
#5 C:\xampp\htdocs\Autologs\protected\framework\zii\widgets\CBaseListView.php(167): CListView->renderItems()
#6 [internal function]: CBaseListView->renderSection(Array)
#7 C:\xampp\htdocs\Autologs\protected\framework\zii\widgets\CBaseListView.php(150): preg_replace_callback('/{(\w+)}/', Array, '{summary}?{sort...')
#8 C:\xampp\htdocs\Autologs\protected\framework\zii\widgets\CBaseListView.php(135): CBaseListView->renderContent()
#9 C:\xampp\htdocs\Autologs\protected\framework\web\CBaseController.php(173): CBaseListView->run()
#10 C:\xampp\htdocs\Autologs\protected\views\Users\index.php(20): CBaseController->widget('zii.widgets.CLi...', Array)
#11 C:\xampp\htdocs\Autologs\protected\framework\web\CBaseController.php(126): require('C:\xampp\htdocs...')
#12 C:\xampp\htdocs\Autologs\protected\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\xampp\htdocs...', Array, true)
#13 C:\xampp\htdocs\Autologs\protected\framework\web\CController.php(869): CBaseController->renderFile('C:\xampp\htdocs...', Array, true)
#14 C:\xampp\htdocs\Autologs\protected\framework\web\CController.php(782): CController->renderPartial('index', Array, true)
#15 C:\xampp\htdocs\Autologs\protected\controllers\UsersController.php(128): CController->render('index', Array)
#16 C:\xampp\htdocs\Autologs\protected\framework\web\actions\CInlineAction.php(49): UsersController->actionIndex()
#17 C:\xampp\htdocs\Autologs\protected\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#18 C:\xampp\htdocs\Autologs\protected\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#19 C:\xampp\htdocs\Autologs\protected\framework\web\filters\CFilter.php(40): CFilterChain->run()
#20 C:\xampp\htdocs\Autologs\protected\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#21 C:\xampp\htdocs\Autologs\protected\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#22 C:\xampp\htdocs\Autologs\protected\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#23 C:\xampp\htdocs\Autologs\protected\framework\web\CController.php(291): CFilterChain->run()
#24 C:\xampp\htdocs\Autologs\protected\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#25 C:\xampp\htdocs\Autologs\protected\framework\web\CWebApplication.php(283): CController->run('index')
#26 C:\xampp\htdocs\Autologs\protected\framework\web\CWebApplication.php(140): CWebApplication->runController('Users/index')
#27 C:\xampp\htdocs\Autologs\protected\framework\base\CApplication.php(180): CWebApplication->processRequest()
#28 C:\xampp\htdocs\Autologs\index.php(13): CApplication->run()
#29 {main}
REQUEST_URI=/Autologs/index.php?r=Users/index
HTTP_REFERER=http://localhost/Autologs/index.php?r=site/index
---
2017/08/27 11:42:53 [error] [php] include(Account.php): failed to open stream: No such file or directory (C:\xampp\htdocs\Autologs\protected\framework\YiiBase.php:427)
Stack trace:
#0 C:\xampp\htdocs\Autologs\protected\controllers\UsersController.php(65): spl_autoload_call()
#1 C:\xampp\htdocs\Autologs\protected\framework\web\actions\CInlineAction.php(49): UsersController->actionCreate()
#2 C:\xampp\htdocs\Autologs\protected\framework\web\CController.php(308): CInlineAction->runWithParams()
#3 C:\xampp\htdocs\Autologs\protected\framework\web\filters\CFilterChain.php(133): UsersController->runAction()
#4 C:\xampp\htdocs\Autologs\protected\framework\web\filters\CFilter.php(40): CFilterChain->run()
#5 C:\xampp\htdocs\Autologs\protected\framework\web\CController.php(1145): CAccessControlFilter->filter()
#6 C:\xampp\htdocs\Autologs\protected\framework\web\filters\CInlineFilter.php(58): UsersController->filterAccessControl()
#7 C:\xampp\htdocs\Autologs\protected\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#8 C:\xampp\htdocs\Autologs\protected\framework\web\CController.php(291): CFilterChain->run()
#9 C:\xampp\htdocs\Autologs\protected\framework\web\CController.php(265): UsersController->runActionWithFilters()
#10 C:\xampp\htdocs\Autologs\protected\framework\web\CWebApplication.php(283): UsersController->run()
#11 C:\xampp\htdocs\Autologs\protected\framework\web\CWebApplication.php(140): CWebApplication->runController()
#12 C:\xampp\htdocs\Autologs\protected\framework\base\CApplication.php(180): CWebApplication->processRequest()
#13 C:\xampp\htdocs\Autologs\index.php(13): CWebApplication->run()
REQUEST_URI=/Autologs/index.php?r=users/create
in C:\xampp\htdocs\Autologs\protected\controllers\UsersController.php (65)
in C:\xampp\htdocs\Autologs\index.php (13)
2017/08/27 11:44:15 [error] [exception.CException] exception 'CException' with message 'Property "Users.password" is not defined.' in C:\xampp\htdocs\Autologs\protected\framework\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\Autologs\protected\framework\db\ar\CActiveRecord.php(145): CComponent->__get('password')
#1 C:\xampp\htdocs\Autologs\protected\framework\web\helpers\CHtml.php(2529): CActiveRecord->__get('password')
#2 C:\xampp\htdocs\Autologs\protected\framework\web\helpers\CHtml.php(2252): CHtml::resolveValue(Object(Users), 'password')
#3 C:\xampp\htdocs\Autologs\protected\framework\web\helpers\CHtml.php(1628): CHtml::activeInputField('password', Object(Users), 'password', Array)
#4 C:\xampp\htdocs\Autologs\protected\framework\web\widgets\CActiveForm.php(771): CHtml::activePasswordField(Object(Users), 'password', Array)
#5 C:\xampp\htdocs\Autologs\protected\views\Users\_form.php(47): CActiveForm->passwordField(Object(Users), 'password', Array)
#6 C:\xampp\htdocs\Autologs\protected\framework\web\CBaseController.php(126): require('C:\xampp\htdocs...')
#7 C:\xampp\htdocs\Autologs\protected\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\xampp\htdocs...', Array, true)
#8 C:\xampp\htdocs\Autologs\protected\framework\web\CController.php(869): CBaseController->renderFile('C:\xampp\htdocs...', Array, true)
#9 C:\xampp\htdocs\Autologs\protected\views\Users\create.php(18): CController->renderPartial('_form', Array)
#10 C:\xampp\htdocs\Autologs\protected\framework\web\CBaseController.php(126): require('C:\xampp\htdocs...')
#11 C:\xampp\htdocs\Autologs\protected\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\xampp\htdocs...', Array, true)
#12 C:\xampp\htdocs\Autologs\protected\framework\web\CController.php(869): CBaseController->renderFile('C:\xampp\htdocs...', Array, true)
#13 C:\xampp\htdocs\Autologs\protected\framework\web\CController.php(782): CController->renderPartial('create', Array, true)
#14 C:\xampp\htdocs\Autologs\protected\controllers\UsersController.php(74): CController->render('create', Array)
#15 C:\xampp\htdocs\Autologs\protected\framework\web\actions\CInlineAction.php(49): UsersController->actionCreate()
#16 C:\xampp\htdocs\Autologs\protected\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#17 C:\xampp\htdocs\Autologs\protected\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#18 C:\xampp\htdocs\Autologs\protected\framework\web\filters\CFilter.php(40): CFilterChain->run()
#19 C:\xampp\htdocs\Autologs\protected\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#20 C:\xampp\htdocs\Autologs\protected\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#21 C:\xampp\htdocs\Autologs\protected\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#22 C:\xampp\htdocs\Autologs\protected\framework\web\CController.php(291): CFilterChain->run()
#23 C:\xampp\htdocs\Autologs\protected\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#24 C:\xampp\htdocs\Autologs\protected\framework\web\CWebApplication.php(283): CController->run('create')
#25 C:\xampp\htdocs\Autologs\protected\framework\web\CWebApplication.php(140): CWebApplication->runController('users/create')
#26 C:\xampp\htdocs\Autologs\protected\framework\base\CApplication.php(180): CWebApplication->processRequest()
#27 C:\xampp\htdocs\Autologs\index.php(13): CApplication->run()
#28 {main}
REQUEST_URI=/Autologs/index.php?r=users/create
HTTP_REFERER=http://localhost/Autologs/index.php?r=site/login
---
2017/08/27 11:44:43 [error] [exception.CException] exception 'CException' with message 'CActiveForm and its behaviors do not have a method or closure named "field".' in C:\xampp\htdocs\Autologs\protected\framework\base\CComponent.php:266
Stack trace:
#0 C:\xampp\htdocs\Autologs\protected\views\Users\_form.php(55): CComponent->__call('field', Array)
#1 C:\xampp\htdocs\Autologs\protected\views\Users\_form.php(55): CActiveForm->field(Object(Users), 'batch')
#2 C:\xampp\htdocs\Autologs\protected\framework\web\CBaseController.php(126): require('C:\xampp\htdocs...')
#3 C:\xampp\htdocs\Autologs\protected\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\xampp\htdocs...', Array, true)
#4 C:\xampp\htdocs\Autologs\protected\framework\web\CController.php(869): CBaseController->renderFile('C:\xampp\htdocs...', Array, true)
#5 C:\xampp\htdocs\Autologs\protected\views\Users\create.php(18): CController->renderPartial('_form', Array)
#6 C:\xampp\htdocs\Autologs\protected\framework\web\CBaseController.php(126): require('C:\xampp\htdocs...')
#7 C:\xampp\htdocs\Autologs\protected\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\xampp\htdocs...', Array, true)
#8 C:\xampp\htdocs\Autologs\protected\framework\web\CController.php(869): CBaseController->renderFile('C:\xampp\htdocs...', Array, true)
#9 C:\xampp\htdocs\Autologs\protected\framework\web\CController.php(782): CController->renderPartial('create', Array, true)
#10 C:\xampp\htdocs\Autologs\protected\controllers\UsersController.php(74): CController->render('create', Array)
#11 C:\xampp\htdocs\Autologs\protected\framework\web\actions\CInlineAction.php(49): UsersController->actionCreate()
#12 C:\xampp\htdocs\Autologs\protected\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#13 C:\xampp\htdocs\Autologs\protected\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#14 C:\xampp\htdocs\Autologs\protected\framework\web\filters\CFilter.php(40): CFilterChain->run()
#15 C:\xampp\htdocs\Autologs\protected\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#16 C:\xampp\htdocs\Autologs\protected\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#17 C:\xampp\htdocs\Autologs\protected\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#18 C:\xampp\htdocs\Autologs\protected\framework\web\CController.php(291): CFilterChain->run()
#19 C:\xampp\htdocs\Autologs\protected\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#20 C:\xampp\htdocs\Autologs\protected\framework\web\CWebApplication.php(283): CController->run('create')
#21 C:\xampp\htdocs\Autologs\protected\framework\web\CWebApplication.php(140): CWebApplication->runController('users/create')
#22 C:\xampp\htdocs\Autologs\protected\framework\base\CApplication.php(180): CWebApplication->processRequest()
#23 C:\xampp\htdocs\Autologs\index.php(13): CApplication->run()
#24 {main}
REQUEST_URI=/Autologs/index.php?r=users/create
HTTP_REFERER=http://localhost/Autologs/index.php?r=site/login
---
2017/08/27 11:46:47 [error] [exception.CException] exception 'CException' with message 'Property "Users.file_import" is not defined.' in C:\xampp\htdocs\Autologs\protected\framework\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\Autologs\protected\framework\db\ar\CActiveRecord.php(145): CComponent->__get('file_import')
#1 C:\xampp\htdocs\Autologs\protected\views\Users\_form.php(61): CActiveRecord->__get('file_import')
#2 C:\xampp\htdocs\Autologs\protected\framework\web\CBaseController.php(126): require('C:\xampp\htdocs...')
#3 C:\xampp\htdocs\Autologs\protected\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\xampp\htdocs...', Array, true)
#4 C:\xampp\htdocs\Autologs\protected\framework\web\CController.php(869): CBaseController->renderFile('C:\xampp\htdocs...', Array, true)
#5 C:\xampp\htdocs\Autologs\protected\views\Users\create.php(18): CController->renderPartial('_form', Array)
#6 C:\xampp\htdocs\Autologs\protected\framework\web\CBaseController.php(126): require('C:\xampp\htdocs...')
#7 C:\xampp\htdocs\Autologs\protected\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\xampp\htdocs...', Array, true)
#8 C:\xampp\htdocs\Autologs\protected\framework\web\CController.php(869): CBaseController->renderFile('C:\xampp\htdocs...', Array, true)
#9 C:\xampp\htdocs\Autologs\protected\framework\web\CController.php(782): CController->renderPartial('create', Array, true)
#10 C:\xampp\htdocs\Autologs\protected\controllers\UsersController.php(74): CController->render('create', Array)
#11 C:\xampp\htdocs\Autologs\protected\framework\web\actions\CInlineAction.php(49): UsersController->actionCreate()
#12 C:\xampp\htdocs\Autologs\protected\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#13 C:\xampp\htdocs\Autologs\protected\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#14 C:\xampp\htdocs\Autologs\protected\framework\web\filters\CFilter.php(40): CFilterChain->run()
#15 C:\xampp\htdocs\Autologs\protected\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#16 C:\xampp\htdocs\Autologs\protected\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#17 C:\xampp\htdocs\Autologs\protected\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#18 C:\xampp\htdocs\Autologs\protected\framework\web\CController.php(291): CFilterChain->run()
#19 C:\xampp\htdocs\Autologs\protected\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#20 C:\xampp\htdocs\Autologs\protected\framework\web\CWebApplication.php(283): CController->run('create')
#21 C:\xampp\htdocs\Autologs\protected\framework\web\CWebApplication.php(140): CWebApplication->runController('users/create')
#22 C:\xampp\htdocs\Autologs\protected\framework\base\CApplication.php(180): CWebApplication->processRequest()
#23 C:\xampp\htdocs\Autologs\index.php(13): CApplication->run()
#24 {main}
REQUEST_URI=/Autologs/index.php?r=users/create
HTTP_REFERER=http://localhost/Autologs/index.php?r=site/login
---
2017/08/27 11:48:24 [error] [exception.CException] exception 'CException' with message 'Property "Users.ac_id" is not defined.' in C:\xampp\htdocs\Autologs\protected\framework\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\Autologs\protected\framework\db\ar\CActiveRecord.php(145): CComponent->__get('ac_id')
#1 C:\xampp\htdocs\Autologs\protected\framework\web\helpers\CHtml.php(2529): CActiveRecord->__get('ac_id')
#2 C:\xampp\htdocs\Autologs\protected\framework\web\helpers\CHtml.php(2252): CHtml::resolveValue(Object(Users), 'ac_id')
#3 C:\xampp\htdocs\Autologs\protected\framework\web\helpers\CHtml.php(1434): CHtml::activeInputField('text', Object(Users), 'ac_id', Array)
#4 C:\xampp\htdocs\Autologs\protected\framework\web\widgets\CActiveForm.php(725): CHtml::activeTextField(Object(Users), 'ac_id', Array)
#5 C:\xampp\htdocs\Autologs\protected\views\Users\_search.php(16): CActiveForm->textField(Object(Users), 'ac_id')
#6 C:\xampp\htdocs\Autologs\protected\framework\web\CBaseController.php(126): require('C:\xampp\htdocs...')
#7 C:\xampp\htdocs\Autologs\protected\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\xampp\htdocs...', Array, true)
#8 C:\xampp\htdocs\Autologs\protected\framework\web\CController.php(869): CBaseController->renderFile('C:\xampp\htdocs...', Array, true)
#9 C:\xampp\htdocs\Autologs\protected\views\Users\admin.php(40): CController->renderPartial('_search', Array)
#10 C:\xampp\htdocs\Autologs\protected\framework\web\CBaseController.php(126): require('C:\xampp\htdocs...')
#11 C:\xampp\htdocs\Autologs\protected\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\xampp\htdocs...', Array, true)
#12 C:\xampp\htdocs\Autologs\protected\framework\web\CController.php(869): CBaseController->renderFile('C:\xampp\htdocs...', Array, true)
#13 C:\xampp\htdocs\Autologs\protected\framework\web\CController.php(782): CController->renderPartial('admin', Array, true)
#14 C:\xampp\htdocs\Autologs\protected\controllers\UsersController.php(133): CController->render('admin', Array)
#15 C:\xampp\htdocs\Autologs\protected\framework\web\actions\CInlineAction.php(49): UsersController->actionAdmin()
#16 C:\xampp\htdocs\Autologs\protected\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#17 C:\xampp\htdocs\Autologs\protected\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#18 C:\xampp\htdocs\Autologs\protected\framework\web\filters\CFilter.php(40): CFilterChain->run()
#19 C:\xampp\htdocs\Autologs\protected\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#20 C:\xampp\htdocs\Autologs\protected\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#21 C:\xampp\htdocs\Autologs\protected\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#22 C:\xampp\htdocs\Autologs\protected\framework\web\CController.php(291): CFilterChain->run()
#23 C:\xampp\htdocs\Autologs\protected\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#24 C:\xampp\htdocs\Autologs\protected\framework\web\CWebApplication.php(283): CController->run('admin')
#25 C:\xampp\htdocs\Autologs\protected\framework\web\CWebApplication.php(140): CWebApplication->runController('users/admin')
#26 C:\xampp\htdocs\Autologs\protected\framework\base\CApplication.php(180): CWebApplication->processRequest()
#27 C:\xampp\htdocs\Autologs\index.php(13): CApplication->run()
#28 {main}
REQUEST_URI=/Autologs/index.php?r=users/admin
HTTP_REFERER=http://localhost/Autologs/index.php?r=users/create
---
2017/08/27 11:49:43 [error] [exception.CException] exception 'CException' with message 'Property "Users.ac_id" is not defined.' in C:\xampp\htdocs\Autologs\protected\framework\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\Autologs\protected\framework\db\ar\CActiveRecord.php(145): CComponent->__get('ac_id')
#1 C:\xampp\htdocs\Autologs\protected\framework\web\helpers\CHtml.php(2529): CActiveRecord->__get('ac_id')
#2 C:\xampp\htdocs\Autologs\protected\framework\web\helpers\CHtml.php(2252): CHtml::resolveValue(Object(Users), 'ac_id')
#3 C:\xampp\htdocs\Autologs\protected\framework\web\helpers\CHtml.php(1434): CHtml::activeInputField('text', Object(Users), 'ac_id', Array)
#4 C:\xampp\htdocs\Autologs\protected\framework\web\widgets\CActiveForm.php(725): CHtml::activeTextField(Object(Users), 'ac_id', Array)
#5 C:\xampp\htdocs\Autologs\protected\views\Users\_search.php(16): CActiveForm->textField(Object(Users), 'ac_id')
#6 C:\xampp\htdocs\Autologs\protected\framework\web\CBaseController.php(126): require('C:\xampp\htdocs...')
#7 C:\xampp\htdocs\Autologs\protected\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\xampp\htdocs...', Array, true)
#8 C:\xampp\htdocs\Autologs\protected\framework\web\CController.php(869): CBaseController->renderFile('C:\xampp\htdocs...', Array, true)
#9 C:\xampp\htdocs\Autologs\protected\views\Users\admin.php(40): CController->renderPartial('_search', Array)
#10 C:\xampp\htdocs\Autologs\protected\framework\web\CBaseController.php(126): require('C:\xampp\htdocs...')
#11 C:\xampp\htdocs\Autologs\protected\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\xampp\htdocs...', Array, true)
#12 C:\xampp\htdocs\Autologs\protected\framework\web\CController.php(869): CBaseController->renderFile('C:\xampp\htdocs...', Array, true)
#13 C:\xampp\htdocs\Autologs\protected\framework\web\CController.php(782): CController->renderPartial('admin', Array, true)
#14 C:\xampp\htdocs\Autologs\protected\controllers\UsersController.php(133): CController->render('admin', Array)
#15 C:\xampp\htdocs\Autologs\protected\framework\web\actions\CInlineAction.php(49): UsersController->actionAdmin()
#16 C:\xampp\htdocs\Autologs\protected\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#17 C:\xampp\htdocs\Autologs\protected\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#18 C:\xampp\htdocs\Autologs\protected\framework\web\filters\CFilter.php(40): CFilterChain->run()
#19 C:\xampp\htdocs\Autologs\protected\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#20 C:\xampp\htdocs\Autologs\protected\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#21 C:\xampp\htdocs\Autologs\protected\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#22 C:\xampp\htdocs\Autologs\protected\framework\web\CController.php(291): CFilterChain->run()
#23 C:\xampp\htdocs\Autologs\protected\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#24 C:\xampp\htdocs\Autologs\protected\framework\web\CWebApplication.php(283): CController->run('admin')
#25 C:\xampp\htdocs\Autologs\protected\framework\web\CWebApplication.php(140): CWebApplication->runController('users/admin')
#26 C:\xampp\htdocs\Autologs\protected\framework\base\CApplication.php(180): CWebApplication->processRequest()
#27 C:\xampp\htdocs\Autologs\index.php(13): CApplication->run()
#28 {main}
REQUEST_URI=/Autologs/index.php?r=users/admin
HTTP_REFERER=http://localhost/Autologs/index.php?r=users/create
---
2017/08/27 11:50:05 [error] [exception.CException] exception 'CException' with message 'Property "Users.ac_id" is not defined.' in C:\xampp\htdocs\Autologs\protected\framework\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\Autologs\protected\framework\db\ar\CActiveRecord.php(145): CComponent->__get('ac_id')
#1 C:\xampp\htdocs\Autologs\protected\framework\web\helpers\CHtml.php(2529): CActiveRecord->__get('ac_id')
#2 C:\xampp\htdocs\Autologs\protected\framework\web\helpers\CHtml.php(2252): CHtml::resolveValue(Object(Users), 'ac_id')
#3 C:\xampp\htdocs\Autologs\protected\framework\web\helpers\CHtml.php(1434): CHtml::activeInputField('text', Object(Users), 'ac_id', Array)
#4 C:\xampp\htdocs\Autologs\protected\framework\zii\widgets\grid\CDataColumn.php(103): CHtml::activeTextField(Object(Users), 'ac_id', Array)
#5 C:\xampp\htdocs\Autologs\protected\framework\zii\widgets\grid\CGridColumn.php(116): CDataColumn->renderFilterCellContent()
#6 C:\xampp\htdocs\Autologs\protected\framework\zii\widgets\grid\CGridView.php(532): CGridColumn->renderFilterCell()
#7 C:\xampp\htdocs\Autologs\protected\framework\zii\widgets\grid\CGridView.php(510): CGridView->renderFilter()
#8 C:\xampp\htdocs\Autologs\protected\framework\zii\widgets\grid\CGridView.php(480): CGridView->renderTableHeader()
#9 C:\xampp\htdocs\Autologs\protected\framework\zii\widgets\CBaseListView.php(167): CGridView->renderItems()
#10 [internal function]: CBaseListView->renderSection(Array)
#11 C:\xampp\htdocs\Autologs\protected\framework\zii\widgets\CBaseListView.php(150): preg_replace_callback('/{(\w+)}/', Array, '{summary}?{item...')
#12 C:\xampp\htdocs\Autologs\protected\framework\zii\widgets\CBaseListView.php(135): CBaseListView->renderContent()
#13 C:\xampp\htdocs\Autologs\protected\framework\web\CBaseController.php(173): CBaseListView->run()
#14 C:\xampp\htdocs\Autologs\protected\views\Users\admin.php(56): CBaseController->widget('zii.widgets.gri...', Array)
#15 C:\xampp\htdocs\Autologs\protected\framework\web\CBaseController.php(126): require('C:\xampp\htdocs...')
#16 C:\xampp\htdocs\Autologs\protected\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\xampp\htdocs...', Array, true)
#17 C:\xampp\htdocs\Autologs\protected\framework\web\CController.php(869): CBaseController->renderFile('C:\xampp\htdocs...', Array, true)
#18 C:\xampp\htdocs\Autologs\protected\framework\web\CController.php(782): CController->renderPartial('admin', Array, true)
#19 C:\xampp\htdocs\Autologs\protected\controllers\UsersController.php(133): CController->render('admin', Array)
#20 C:\xampp\htdocs\Autologs\protected\framework\web\actions\CInlineAction.php(49): UsersController->actionAdmin()
#21 C:\xampp\htdocs\Autologs\protected\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#22 C:\xampp\htdocs\Autologs\protected\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#23 C:\xampp\htdocs\Autologs\protected\framework\web\filters\CFilter.php(40): CFilterChain->run()
#24 C:\xampp\htdocs\Autologs\protected\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#25 C:\xampp\htdocs\Autologs\protected\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#26 C:\xampp\htdocs\Autologs\protected\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#27 C:\xampp\htdocs\Autologs\protected\framework\web\CController.php(291): CFilterChain->run()
#28 C:\xampp\htdocs\Autologs\protected\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#29 C:\xampp\htdocs\Autologs\protected\framework\web\CWebApplication.php(283): CController->run('admin')
#30 C:\xampp\htdocs\Autologs\protected\framework\web\CWebApplication.php(140): CWebApplication->runController('users/admin')
#31 C:\xampp\htdocs\Autologs\protected\framework\base\CApplication.php(180): CWebApplication->processRequest()
#32 C:\xampp\htdocs\Autologs\index.php(13): CApplication->run()
#33 {main}
REQUEST_URI=/Autologs/index.php?r=users/admin
HTTP_REFERER=http://localhost/Autologs/index.php?r=users/create
---
2017/08/27 11:52:02 [error] [exception.CException] exception 'CException' with message 'Property "Users.ac_id" is not defined.' in C:\xampp\htdocs\Autologs\protected\framework\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\Autologs\protected\framework\db\ar\CActiveRecord.php(145): CComponent->__get('ac_id')
#1 C:\xampp\htdocs\Autologs\protected\views\Users\view.php(7): CActiveRecord->__get('ac_id')
#2 C:\xampp\htdocs\Autologs\protected\framework\web\CBaseController.php(126): require('C:\xampp\htdocs...')
#3 C:\xampp\htdocs\Autologs\protected\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\xampp\htdocs...', Array, true)
#4 C:\xampp\htdocs\Autologs\protected\framework\web\CController.php(869): CBaseController->renderFile('C:\xampp\htdocs...', Array, true)
#5 C:\xampp\htdocs\Autologs\protected\framework\web\CController.php(782): CController->renderPartial('view', Array, true)
#6 C:\xampp\htdocs\Autologs\protected\controllers\UsersController.php(53): CController->render('view', Array)
#7 [internal function]: UsersController->actionView('1')
#8 C:\xampp\htdocs\Autologs\protected\framework\web\actions\CAction.php(108): ReflectionMethod->invokeArgs(Object(UsersController), Array)
#9 C:\xampp\htdocs\Autologs\protected\framework\web\actions\CInlineAction.php(47): CAction->runWithParamsInternal(Object(UsersController), Object(ReflectionMethod), Array)
#10 C:\xampp\htdocs\Autologs\protected\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#11 C:\xampp\htdocs\Autologs\protected\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#12 C:\xampp\htdocs\Autologs\protected\framework\web\filters\CFilter.php(40): CFilterChain->run()
#13 C:\xampp\htdocs\Autologs\protected\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#14 C:\xampp\htdocs\Autologs\protected\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#15 C:\xampp\htdocs\Autologs\protected\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#16 C:\xampp\htdocs\Autologs\protected\framework\web\CController.php(291): CFilterChain->run()
#17 C:\xampp\htdocs\Autologs\protected\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#18 C:\xampp\htdocs\Autologs\protected\framework\web\CWebApplication.php(283): CController->run('view')
#19 C:\xampp\htdocs\Autologs\protected\framework\web\CWebApplication.php(140): CWebApplication->runController('users/view')
#20 C:\xampp\htdocs\Autologs\protected\framework\base\CApplication.php(180): CWebApplication->processRequest()
#21 C:\xampp\htdocs\Autologs\index.php(13): CApplication->run()
#22 {main}
REQUEST_URI=/Autologs/index.php?r=users/view&id=1
HTTP_REFERER=http://localhost/Autologs/index.php?r=users/admin
---
2017/08/27 11:53:49 [error] [exception.CException] exception 'CException' with message 'Property "Users.ac_id" is not defined.' in C:\xampp\htdocs\Autologs\protected\framework\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\Autologs\protected\framework\db\ar\CActiveRecord.php(145): CComponent->__get('ac_id')
#1 C:\xampp\htdocs\Autologs\protected\views\Users\view.php(7): CActiveRecord->__get('ac_id')
#2 C:\xampp\htdocs\Autologs\protected\framework\web\CBaseController.php(126): require('C:\xampp\htdocs...')
#3 C:\xampp\htdocs\Autologs\protected\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\xampp\htdocs...', Array, true)
#4 C:\xampp\htdocs\Autologs\protected\framework\web\CController.php(869): CBaseController->renderFile('C:\xampp\htdocs...', Array, true)
#5 C:\xampp\htdocs\Autologs\protected\framework\web\CController.php(782): CController->renderPartial('view', Array, true)
#6 C:\xampp\htdocs\Autologs\protected\controllers\UsersController.php(53): CController->render('view', Array)
#7 [internal function]: UsersController->actionView('1')
#8 C:\xampp\htdocs\Autologs\protected\framework\web\actions\CAction.php(108): ReflectionMethod->invokeArgs(Object(UsersController), Array)
#9 C:\xampp\htdocs\Autologs\protected\framework\web\actions\CInlineAction.php(47): CAction->runWithParamsInternal(Object(UsersController), Object(ReflectionMethod), Array)
#10 C:\xampp\htdocs\Autologs\protected\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#11 C:\xampp\htdocs\Autologs\protected\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#12 C:\xampp\htdocs\Autologs\protected\framework\web\filters\CFilter.php(40): CFilterChain->run()
#13 C:\xampp\htdocs\Autologs\protected\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#14 C:\xampp\htdocs\Autologs\protected\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#15 C:\xampp\htdocs\Autologs\protected\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#16 C:\xampp\htdocs\Autologs\protected\framework\web\CController.php(291): CFilterChain->run()
#17 C:\xampp\htdocs\Autologs\protected\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#18 C:\xampp\htdocs\Autologs\protected\framework\web\CWebApplication.php(283): CController->run('view')
#19 C:\xampp\htdocs\Autologs\protected\framework\web\CWebApplication.php(140): CWebApplication->runController('users/view')
#20 C:\xampp\htdocs\Autologs\protected\framework\base\CApplication.php(180): CWebApplication->processRequest()
#21 C:\xampp\htdocs\Autologs\index.php(13): CApplication->run()
#22 {main}
REQUEST_URI=/Autologs/index.php?r=users/view&id=1
HTTP_REFERER=http://localhost/Autologs/index.php?r=users/admin
---
2017/08/27 11:54:19 [error] [exception.CException] exception 'CException' with message 'Property "Users.ac_id" is not defined.' in C:\xampp\htdocs\Autologs\protected\framework\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\Autologs\protected\framework\db\ar\CActiveRecord.php(145): CComponent->__get('ac_id')
#1 C:\xampp\htdocs\Autologs\protected\views\Users\view.php(7): CActiveRecord->__get('ac_id')
#2 C:\xampp\htdocs\Autologs\protected\framework\web\CBaseController.php(126): require('C:\xampp\htdocs...')
#3 C:\xampp\htdocs\Autologs\protected\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\xampp\htdocs...', Array, true)
#4 C:\xampp\htdocs\Autologs\protected\framework\web\CController.php(869): CBaseController->renderFile('C:\xampp\htdocs...', Array, true)
#5 C:\xampp\htdocs\Autologs\protected\framework\web\CController.php(782): CController->renderPartial('view', Array, true)
#6 C:\xampp\htdocs\Autologs\protected\controllers\UsersController.php(53): CController->render('view', Array)
#7 [internal function]: UsersController->actionView('1')
#8 C:\xampp\htdocs\Autologs\protected\framework\web\actions\CAction.php(108): ReflectionMethod->invokeArgs(Object(UsersController), Array)
#9 C:\xampp\htdocs\Autologs\protected\framework\web\actions\CInlineAction.php(47): CAction->runWithParamsInternal(Object(UsersController), Object(ReflectionMethod), Array)
#10 C:\xampp\htdocs\Autologs\protected\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#11 C:\xampp\htdocs\Autologs\protected\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#12 C:\xampp\htdocs\Autologs\protected\framework\web\filters\CFilter.php(40): CFilterChain->run()
#13 C:\xampp\htdocs\Autologs\protected\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#14 C:\xampp\htdocs\Autologs\protected\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#15 C:\xampp\htdocs\Autologs\protected\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#16 C:\xampp\htdocs\Autologs\protected\framework\web\CController.php(291): CFilterChain->run()
#17 C:\xampp\htdocs\Autologs\protected\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#18 C:\xampp\htdocs\Autologs\protected\framework\web\CWebApplication.php(283): CController->run('view')
#19 C:\xampp\htdocs\Autologs\protected\framework\web\CWebApplication.php(140): CWebApplication->runController('users/view')
#20 C:\xampp\htdocs\Autologs\protected\framework\base\CApplication.php(180): CWebApplication->processRequest()
#21 C:\xampp\htdocs\Autologs\index.php(13): CApplication->run()
#22 {main}
REQUEST_URI=/Autologs/index.php?r=users/view&id=1
HTTP_REFERER=http://localhost/Autologs/index.php?r=users/admin
---
2017/08/27 11:55:04 [error] [exception.CException] exception 'CException' with message 'Property "Users.ac_id" is not defined.' in C:\xampp\htdocs\Autologs\protected\framework\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\Autologs\protected\framework\db\ar\CActiveRecord.php(145): CComponent->__get('ac_id')
#1 C:\xampp\htdocs\Autologs\protected\views\Users\update.php(7): CActiveRecord->__get('ac_id')
#2 C:\xampp\htdocs\Autologs\protected\framework\web\CBaseController.php(126): require('C:\xampp\htdocs...')
#3 C:\xampp\htdocs\Autologs\protected\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\xampp\htdocs...', Array, true)
#4 C:\xampp\htdocs\Autologs\protected\framework\web\CController.php(869): CBaseController->renderFile('C:\xampp\htdocs...', Array, true)
#5 C:\xampp\htdocs\Autologs\protected\framework\web\CController.php(782): CController->renderPartial('update', Array, true)
#6 C:\xampp\htdocs\Autologs\protected\controllers\UsersController.php(96): CController->render('update', Array)
#7 [internal function]: UsersController->actionUpdate('1')
#8 C:\xampp\htdocs\Autologs\protected\framework\web\actions\CAction.php(108): ReflectionMethod->invokeArgs(Object(UsersController), Array)
#9 C:\xampp\htdocs\Autologs\protected\framework\web\actions\CInlineAction.php(47): CAction->runWithParamsInternal(Object(UsersController), Object(ReflectionMethod), Array)
#10 C:\xampp\htdocs\Autologs\protected\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#11 C:\xampp\htdocs\Autologs\protected\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#12 C:\xampp\htdocs\Autologs\protected\framework\web\filters\CFilter.php(40): CFilterChain->run()
#13 C:\xampp\htdocs\Autologs\protected\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#14 C:\xampp\htdocs\Autologs\protected\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#15 C:\xampp\htdocs\Autologs\protected\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#16 C:\xampp\htdocs\Autologs\protected\framework\web\CController.php(291): CFilterChain->run()
#17 C:\xampp\htdocs\Autologs\protected\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#18 C:\xampp\htdocs\Autologs\protected\framework\web\CWebApplication.php(283): CController->run('update')
#19 C:\xampp\htdocs\Autologs\protected\framework\web\CWebApplication.php(140): CWebApplication->runController('users/update')
#20 C:\xampp\htdocs\Autologs\protected\framework\base\CApplication.php(180): CWebApplication->processRequest()
#21 C:\xampp\htdocs\Autologs\index.php(13): CApplication->run()
#22 {main}
REQUEST_URI=/Autologs/index.php?r=users/update&id=1
HTTP_REFERER=http://localhost/Autologs/index.php?r=users/view&id=1
---
2017/08/27 11:55:35 [error] [exception.CException] exception 'CException' with message 'Property "Users.ac_id" is not defined.' in C:\xampp\htdocs\Autologs\protected\framework\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\Autologs\protected\framework\db\ar\CActiveRecord.php(145): CComponent->__get('ac_id')
#1 C:\xampp\htdocs\Autologs\protected\views\Users\update.php(19): CActiveRecord->__get('ac_id')
#2 C:\xampp\htdocs\Autologs\protected\framework\web\CBaseController.php(126): require('C:\xampp\htdocs...')
#3 C:\xampp\htdocs\Autologs\protected\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\xampp\htdocs...', Array, true)
#4 C:\xampp\htdocs\Autologs\protected\framework\web\CController.php(869): CBaseController->renderFile('C:\xampp\htdocs...', Array, true)
#5 C:\xampp\htdocs\Autologs\protected\framework\web\CController.php(782): CController->renderPartial('update', Array, true)
#6 C:\xampp\htdocs\Autologs\protected\controllers\UsersController.php(96): CController->render('update', Array)
#7 [internal function]: UsersController->actionUpdate('1')
#8 C:\xampp\htdocs\Autologs\protected\framework\web\actions\CAction.php(108): ReflectionMethod->invokeArgs(Object(UsersController), Array)
#9 C:\xampp\htdocs\Autologs\protected\framework\web\actions\CInlineAction.php(47): CAction->runWithParamsInternal(Object(UsersController), Object(ReflectionMethod), Array)
#10 C:\xampp\htdocs\Autologs\protected\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#11 C:\xampp\htdocs\Autologs\protected\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#12 C:\xampp\htdocs\Autologs\protected\framework\web\filters\CFilter.php(40): CFilterChain->run()
#13 C:\xampp\htdocs\Autologs\protected\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#14 C:\xampp\htdocs\Autologs\protected\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#15 C:\xampp\htdocs\Autologs\protected\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#16 C:\xampp\htdocs\Autologs\protected\framework\web\CController.php(291): CFilterChain->run()
#17 C:\xampp\htdocs\Autologs\protected\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#18 C:\xampp\htdocs\Autologs\protected\framework\web\CWebApplication.php(283): CController->run('update')
#19 C:\xampp\htdocs\Autologs\protected\framework\web\CWebApplication.php(140): CWebApplication->runController('users/update')
#20 C:\xampp\htdocs\Autologs\protected\framework\base\CApplication.php(180): CWebApplication->processRequest()
#21 C:\xampp\htdocs\Autologs\index.php(13): CApplication->run()
#22 {main}
REQUEST_URI=/Autologs/index.php?r=users/update&id=1
HTTP_REFERER=http://localhost/Autologs/index.php?r=users/view&id=1
---
2017/08/27 12:12:58 [error] [exception.CException] exception 'CException' with message 'Property "CButtonColumn.title" is not defined.' in C:\xampp\htdocs\Autologs\protected\framework\base\CComponent.php:173
Stack trace:
#0 C:\xampp\htdocs\Autologs\protected\framework\YiiBase.php(220): CComponent->__set('title', 'Actions')
#1 C:\xampp\htdocs\Autologs\protected\framework\zii\widgets\grid\CGridView.php(388): YiiBase::createComponent(Array, Object(CGridView))
#2 C:\xampp\htdocs\Autologs\protected\framework\zii\widgets\grid\CGridView.php(359): CGridView->initColumns()
#3 C:\xampp\htdocs\Autologs\protected\framework\web\CBaseController.php(147): CGridView->init()
#4 C:\xampp\htdocs\Autologs\protected\framework\web\CBaseController.php(172): CBaseController->createWidget('zii.widgets.gri...', Array)
#5 C:\xampp\htdocs\Autologs\protected\views\Users\admin.php(58): CBaseController->widget('zii.widgets.gri...', Array)
#6 C:\xampp\htdocs\Autologs\protected\framework\web\CBaseController.php(126): require('C:\xampp\htdocs...')
#7 C:\xampp\htdocs\Autologs\protected\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\xampp\htdocs...', Array, true)
#8 C:\xampp\htdocs\Autologs\protected\framework\web\CController.php(869): CBaseController->renderFile('C:\xampp\htdocs...', Array, true)
#9 C:\xampp\htdocs\Autologs\protected\framework\web\CController.php(782): CController->renderPartial('admin', Array, true)
#10 C:\xampp\htdocs\Autologs\protected\controllers\UsersController.php(133): CController->render('admin', Array)
#11 C:\xampp\htdocs\Autologs\protected\framework\web\actions\CInlineAction.php(49): UsersController->actionAdmin()
#12 C:\xampp\htdocs\Autologs\protected\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#13 C:\xampp\htdocs\Autologs\protected\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#14 C:\xampp\htdocs\Autologs\protected\framework\web\filters\CFilter.php(40): CFilterChain->run()
#15 C:\xampp\htdocs\Autologs\protected\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#16 C:\xampp\htdocs\Autologs\protected\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#17 C:\xampp\htdocs\Autologs\protected\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#18 C:\xampp\htdocs\Autologs\protected\framework\web\CController.php(291): CFilterChain->run()
#19 C:\xampp\htdocs\Autologs\protected\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#20 C:\xampp\htdocs\Autologs\protected\framework\web\CWebApplication.php(283): CController->run('admin')
#21 C:\xampp\htdocs\Autologs\protected\framework\web\CWebApplication.php(140): CWebApplication->runController('users/admin')
#22 C:\xampp\htdocs\Autologs\protected\framework\base\CApplication.php(180): CWebApplication->processRequest()
#23 C:\xampp\htdocs\Autologs\index.php(13): CApplication->run()
#24 {main}
REQUEST_URI=/Autologs/index.php?r=users/admin
HTTP_REFERER=http://localhost/Autologs/index.php?r=users/view&id=1
---
2017/08/27 12:22:11 [error] [exception.CException] exception 'CException' with message 'Property "Users.Field1" is not defined.' in C:\xampp\htdocs\Autologs\protected\framework\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\Autologs\protected\framework\db\ar\CActiveRecord.php(145): CComponent->__get('Field1')
#1 C:\xampp\htdocs\Autologs\protected\framework\web\helpers\CHtml.php(2529): CActiveRecord->__get('Field1')
#2 C:\xampp\htdocs\Autologs\protected\framework\web\helpers\CHtml.php(2252): CHtml::resolveValue(Object(Users), 'Field1')
#3 C:\xampp\htdocs\Autologs\protected\framework\web\helpers\CHtml.php(1434): CHtml::activeInputField('text', Object(Users), 'Field1', Array)
#4 C:\xampp\htdocs\Autologs\protected\framework\zii\widgets\grid\CDataColumn.php(103): CHtml::activeTextField(Object(Users), 'Field1', Array)
#5 C:\xampp\htdocs\Autologs\protected\framework\zii\widgets\grid\CGridColumn.php(116): CDataColumn->renderFilterCellContent()
#6 C:\xampp\htdocs\Autologs\protected\framework\zii\widgets\grid\CGridView.php(532): CGridColumn->renderFilterCell()
#7 C:\xampp\htdocs\Autologs\protected\framework\zii\widgets\grid\CGridView.php(510): CGridView->renderFilter()
#8 C:\xampp\htdocs\Autologs\protected\framework\zii\widgets\grid\CGridView.php(480): CGridView->renderTableHeader()
#9 C:\xampp\htdocs\Autologs\protected\framework\zii\widgets\CBaseListView.php(167): CGridView->renderItems()
#10 [internal function]: CBaseListView->renderSection(Array)
#11 C:\xampp\htdocs\Autologs\protected\framework\zii\widgets\CBaseListView.php(150): preg_replace_callback('/{(\w+)}/', Array, '{summary}?{item...')
#12 C:\xampp\htdocs\Autologs\protected\framework\zii\widgets\CBaseListView.php(135): CBaseListView->renderContent()
#13 C:\xampp\htdocs\Autologs\protected\framework\web\CBaseController.php(173): CBaseListView->run()
#14 C:\xampp\htdocs\Autologs\protected\views\site\index.php(64): CBaseController->widget('zii.widgets.gri...', Array)
#15 C:\xampp\htdocs\Autologs\protected\framework\web\CBaseController.php(126): require('C:\xampp\htdocs...')
#16 C:\xampp\htdocs\Autologs\protected\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\xampp\htdocs...', Array, true)
#17 C:\xampp\htdocs\Autologs\protected\framework\web\CController.php(869): CBaseController->renderFile('C:\xampp\htdocs...', Array, true)
#18 C:\xampp\htdocs\Autologs\protected\framework\web\CController.php(782): CController->renderPartial('index', Array, true)
#19 C:\xampp\htdocs\Autologs\protected\controllers\SiteController.php(33): CController->render('index', Array)
#20 C:\xampp\htdocs\Autologs\protected\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#21 C:\xampp\htdocs\Autologs\protected\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#22 C:\xampp\htdocs\Autologs\protected\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#23 C:\xampp\htdocs\Autologs\protected\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#24 C:\xampp\htdocs\Autologs\protected\framework\web\CWebApplication.php(283): CController->run('index')
#25 C:\xampp\htdocs\Autologs\protected\framework\web\CWebApplication.php(140): CWebApplication->runController('site/index')
#26 C:\xampp\htdocs\Autologs\protected\framework\base\CApplication.php(180): CWebApplication->processRequest()
#27 C:\xampp\htdocs\Autologs\index.php(13): CApplication->run()
#28 {main}
REQUEST_URI=/Autologs/index.php?r=site/index
HTTP_REFERER=http://localhost/Autologs/index.php?r=users/admin
---
2017/08/27 14:34:42 [error] [exception.CException] exception 'CException' with message 'SiteController has an extra endWidget() call in its view.' in C:\xampp\htdocs\Autologs\protected\framework\web\CBaseController.php:210
Stack trace:
#0 C:\xampp\htdocs\Autologs\protected\views\site\logtabs.php(24): CBaseController->endWidget()
#1 C:\xampp\htdocs\Autologs\protected\framework\web\CBaseController.php(126): require('C:\xampp\htdocs...')
#2 C:\xampp\htdocs\Autologs\protected\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\xampp\htdocs...', NULL, true)
#3 C:\xampp\htdocs\Autologs\protected\framework\web\CController.php(869): CBaseController->renderFile('C:\xampp\htdocs...', NULL, true)
#4 C:\xampp\htdocs\Autologs\protected\views\site\index.php(11): CController->renderPartial('logtabs')
#5 C:\xampp\htdocs\Autologs\protected\framework\web\CBaseController.php(126): require('C:\xampp\htdocs...')
#6 C:\xampp\htdocs\Autologs\protected\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\xampp\htdocs...', Array, true)
#7 C:\xampp\htdocs\Autologs\protected\framework\web\CController.php(869): CBaseController->renderFile('C:\xampp\htdocs...', Array, true)
#8 C:\xampp\htdocs\Autologs\protected\framework\web\CController.php(782): CController->renderPartial('index', Array, true)
#9 C:\xampp\htdocs\Autologs\protected\controllers\SiteController.php(33): CController->render('index', Array)
#10 C:\xampp\htdocs\Autologs\protected\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#11 C:\xampp\htdocs\Autologs\protected\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#12 C:\xampp\htdocs\Autologs\protected\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#13 C:\xampp\htdocs\Autologs\protected\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#14 C:\xampp\htdocs\Autologs\protected\framework\web\CWebApplication.php(283): CController->run('index')
#15 C:\xampp\htdocs\Autologs\protected\framework\web\CWebApplication.php(140): CWebApplication->runController('site/index')
#16 C:\xampp\htdocs\Autologs\protected\framework\base\CApplication.php(180): CWebApplication->processRequest()
#17 C:\xampp\htdocs\Autologs\index.php(13): CApplication->run()
#18 {main}
REQUEST_URI=/Autologs/index.php?r=site/index
HTTP_REFERER=http://localhost/Autologs/index.php?r=users/admin
---
2017/08/27 15:13:02 [error] [php] Object of class Userapps could not be converted to string (C:\xampp\htdocs\Autologs\protected\views\site\logtabs.php:8)
Stack trace:
#0 C:\xampp\htdocs\Autologs\framework\web\CBaseController.php(95): SiteController->renderInternal()
#1 C:\xampp\htdocs\Autologs\framework\web\CController.php(869): SiteController->renderFile()
#2 C:\xampp\htdocs\Autologs\protected\views\site\index.php(11): SiteController->renderPartial()
#3 C:\xampp\htdocs\Autologs\framework\web\CBaseController.php(126): require()
#4 C:\xampp\htdocs\Autologs\framework\web\CBaseController.php(95): SiteController->renderInternal()
#5 C:\xampp\htdocs\Autologs\framework\web\CController.php(869): SiteController->renderFile()
#6 C:\xampp\htdocs\Autologs\framework\web\CController.php(782): SiteController->renderPartial()
#7 C:\xampp\htdocs\Autologs\protected\controllers\SiteController.php(34): SiteController->render()
#8 C:\xampp\htdocs\Autologs\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#9 C:\xampp\htdocs\Autologs\framework\web\CController.php(308): CInlineAction->runWithParams()
#10 C:\xampp\htdocs\Autologs\framework\web\CController.php(286): SiteController->runAction()
#11 C:\xampp\htdocs\Autologs\framework\web\CController.php(265): SiteController->runActionWithFilters()
#12 C:\xampp\htdocs\Autologs\framework\web\CWebApplication.php(283): SiteController->run()
#13 C:\xampp\htdocs\Autologs\framework\web\CWebApplication.php(140): CWebApplication->runController()
#14 C:\xampp\htdocs\Autologs\framework\base\CApplication.php(180): CWebApplication->processRequest()
#15 C:\xampp\htdocs\Autologs\index.php(13): CWebApplication->run()
REQUEST_URI=/Autologs/index.php
in C:\xampp\htdocs\Autologs\protected\views\site\logtabs.php (8)
in C:\xampp\htdocs\Autologs\protected\views\site\index.php (11)
in C:\xampp\htdocs\Autologs\protected\controllers\SiteController.php (34)
2017/08/27 15:14:18 [error] [php] Invalid argument supplied for foreach() (C:\xampp\htdocs\Autologs\protected\views\site\logtabs.php:7)
Stack trace:
#0 C:\xampp\htdocs\Autologs\framework\web\CController.php(869): SiteController->renderFile()
#1 C:\xampp\htdocs\Autologs\protected\views\site\index.php(11): SiteController->renderPartial()
#2 C:\xampp\htdocs\Autologs\framework\web\CBaseController.php(126): require()
#3 C:\xampp\htdocs\Autologs\framework\web\CBaseController.php(95): SiteController->renderInternal()
#4 C:\xampp\htdocs\Autologs\framework\web\CController.php(869): SiteController->renderFile()
#5 C:\xampp\htdocs\Autologs\framework\web\CController.php(782): SiteController->renderPartial()
#6 C:\xampp\htdocs\Autologs\protected\controllers\SiteController.php(34): SiteController->render()
#7 C:\xampp\htdocs\Autologs\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#8 C:\xampp\htdocs\Autologs\framework\web\CController.php(308): CInlineAction->runWithParams()
#9 C:\xampp\htdocs\Autologs\framework\web\CController.php(286): SiteController->runAction()
#10 C:\xampp\htdocs\Autologs\framework\web\CController.php(265): SiteController->runActionWithFilters()
#11 C:\xampp\htdocs\Autologs\framework\web\CWebApplication.php(283): SiteController->run()
#12 C:\xampp\htdocs\Autologs\framework\web\CWebApplication.php(140): CWebApplication->runController()
#13 C:\xampp\htdocs\Autologs\framework\base\CApplication.php(180): CWebApplication->processRequest()
#14 C:\xampp\htdocs\Autologs\index.php(13): CWebApplication->run()
REQUEST_URI=/Autologs/index.php
in C:\xampp\htdocs\Autologs\protected\views\site\logtabs.php (7)
in C:\xampp\htdocs\Autologs\protected\views\site\index.php (11)
in C:\xampp\htdocs\Autologs\protected\controllers\SiteController.php (34)
2017/08/27 15:18:20 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1. The SQL statement executed was: SELECT `appname`  FROM `tbuserapps` WHERE `userid`=.
in C:\xampp\htdocs\Autologs\protected\models\userapps.php (108)
in C:\xampp\htdocs\Autologs\protected\views\site\logtabs.php (4)
in C:\xampp\htdocs\Autologs\protected\views\site\index.php (11)
2017/08/27 15:18:20 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1. The SQL statement executed was: SELECT `appname`  FROM `tbuserapps` WHERE `userid`=' in C:\xampp\htdocs\Autologs\framework\db\CDbCommand.php:543
Stack trace:
#0 C:\xampp\htdocs\Autologs\framework\db\CDbCommand.php(396): CDbCommand->queryInternal('fetchAll', Array, Array)
#1 C:\xampp\htdocs\Autologs\protected\models\userapps.php(108): CDbCommand->queryAll()
#2 C:\xampp\htdocs\Autologs\protected\views\site\logtabs.php(4): Userapps->searchApps()
#3 C:\xampp\htdocs\Autologs\framework\web\CBaseController.php(126): require('C:\xampp\htdocs...')
#4 C:\xampp\htdocs\Autologs\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\xampp\htdocs...', Array, true)
#5 C:\xampp\htdocs\Autologs\framework\web\CController.php(869): CBaseController->renderFile('C:\xampp\htdocs...', Array, true)
#6 C:\xampp\htdocs\Autologs\protected\views\site\index.php(11): CController->renderPartial('logtabs', Array)
#7 C:\xampp\htdocs\Autologs\framework\web\CBaseController.php(126): require('C:\xampp\htdocs...')
#8 C:\xampp\htdocs\Autologs\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\xampp\htdocs...', Array, true)
#9 C:\xampp\htdocs\Autologs\framework\web\CController.php(869): CBaseController->renderFile('C:\xampp\htdocs...', Array, true)
#10 C:\xampp\htdocs\Autologs\framework\web\CController.php(782): CController->renderPartial('index', Array, true)
#11 C:\xampp\htdocs\Autologs\protected\controllers\SiteController.php(34): CController->render('index', Array)
#12 C:\xampp\htdocs\Autologs\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#13 C:\xampp\htdocs\Autologs\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#14 C:\xampp\htdocs\Autologs\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#15 C:\xampp\htdocs\Autologs\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#16 C:\xampp\htdocs\Autologs\framework\web\CWebApplication.php(283): CController->run('')
#17 C:\xampp\htdocs\Autologs\framework\web\CWebApplication.php(140): CWebApplication->runController('')
#18 C:\xampp\htdocs\Autologs\framework\base\CApplication.php(180): CWebApplication->processRequest()
#19 C:\xampp\htdocs\Autologs\index.php(13): CApplication->run()
#20 {main}
REQUEST_URI=/Autologs/index.php
HTTP_REFERER=http://localhost/Autologs/index.php?r=site/index
---
2017/08/27 15:19:00 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1. The SQL statement executed was: SELECT `appname`  FROM `tbuserapps` WHERE `userid`=.
in C:\xampp\htdocs\Autologs\protected\models\userapps.php (108)
in C:\xampp\htdocs\Autologs\protected\views\site\logtabs.php (5)
in C:\xampp\htdocs\Autologs\protected\views\site\index.php (11)
2017/08/27 15:19:00 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1. The SQL statement executed was: SELECT `appname`  FROM `tbuserapps` WHERE `userid`=' in C:\xampp\htdocs\Autologs\framework\db\CDbCommand.php:543
Stack trace:
#0 C:\xampp\htdocs\Autologs\framework\db\CDbCommand.php(396): CDbCommand->queryInternal('fetchAll', Array, Array)
#1 C:\xampp\htdocs\Autologs\protected\models\userapps.php(108): CDbCommand->queryAll()
#2 C:\xampp\htdocs\Autologs\protected\views\site\logtabs.php(5): Userapps->searchApps()
#3 C:\xampp\htdocs\Autologs\framework\web\CBaseController.php(126): require('C:\xampp\htdocs...')
#4 C:\xampp\htdocs\Autologs\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\xampp\htdocs...', Array, true)
#5 C:\xampp\htdocs\Autologs\framework\web\CController.php(869): CBaseController->renderFile('C:\xampp\htdocs...', Array, true)
#6 C:\xampp\htdocs\Autologs\protected\views\site\index.php(11): CController->renderPartial('logtabs', Array)
#7 C:\xampp\htdocs\Autologs\framework\web\CBaseController.php(126): require('C:\xampp\htdocs...')
#8 C:\xampp\htdocs\Autologs\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\xampp\htdocs...', Array, true)
#9 C:\xampp\htdocs\Autologs\framework\web\CController.php(869): CBaseController->renderFile('C:\xampp\htdocs...', Array, true)
#10 C:\xampp\htdocs\Autologs\framework\web\CController.php(782): CController->renderPartial('index', Array, true)
#11 C:\xampp\htdocs\Autologs\protected\controllers\SiteController.php(34): CController->render('index', Array)
#12 C:\xampp\htdocs\Autologs\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#13 C:\xampp\htdocs\Autologs\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#14 C:\xampp\htdocs\Autologs\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#15 C:\xampp\htdocs\Autologs\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#16 C:\xampp\htdocs\Autologs\framework\web\CWebApplication.php(283): CController->run('')
#17 C:\xampp\htdocs\Autologs\framework\web\CWebApplication.php(140): CWebApplication->runController('')
#18 C:\xampp\htdocs\Autologs\framework\base\CApplication.php(180): CWebApplication->processRequest()
#19 C:\xampp\htdocs\Autologs\index.php(13): CApplication->run()
#20 {main}
REQUEST_URI=/Autologs/index.php
HTTP_REFERER=http://localhost/Autologs/index.php?r=site/index
---
2017/08/27 15:20:54 [error] [php] Undefined variable: model (C:\xampp\htdocs\Autologs\protected\controllers\SiteController.php:33)
Stack trace:
#0 C:\xampp\htdocs\Autologs\framework\web\CController.php(286): SiteController->runAction()
#1 C:\xampp\htdocs\Autologs\framework\web\CController.php(265): SiteController->runActionWithFilters()
#2 C:\xampp\htdocs\Autologs\framework\web\CWebApplication.php(283): SiteController->run()
#3 C:\xampp\htdocs\Autologs\framework\web\CWebApplication.php(140): CWebApplication->runController()
#4 C:\xampp\htdocs\Autologs\framework\base\CApplication.php(180): CWebApplication->processRequest()
#5 C:\xampp\htdocs\Autologs\index.php(13): CWebApplication->run()
REQUEST_URI=/Autologs/index.php
in C:\xampp\htdocs\Autologs\protected\controllers\SiteController.php (33)
in C:\xampp\htdocs\Autologs\index.php (13)
2017/08/27 15:21:45 [error] [php] Invalid argument supplied for foreach() (C:\xampp\htdocs\Autologs\protected\views\site\logtabs.php:8)
Stack trace:
#0 C:\xampp\htdocs\Autologs\framework\web\CController.php(869): SiteController->renderFile()
#1 C:\xampp\htdocs\Autologs\protected\views\site\index.php(11): SiteController->renderPartial()
#2 C:\xampp\htdocs\Autologs\framework\web\CBaseController.php(126): require()
#3 C:\xampp\htdocs\Autologs\framework\web\CBaseController.php(95): SiteController->renderInternal()
#4 C:\xampp\htdocs\Autologs\framework\web\CController.php(869): SiteController->renderFile()
#5 C:\xampp\htdocs\Autologs\framework\web\CController.php(782): SiteController->renderPartial()
#6 C:\xampp\htdocs\Autologs\protected\controllers\SiteController.php(34): SiteController->render()
#7 C:\xampp\htdocs\Autologs\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#8 C:\xampp\htdocs\Autologs\framework\web\CController.php(308): CInlineAction->runWithParams()
#9 C:\xampp\htdocs\Autologs\framework\web\CController.php(286): SiteController->runAction()
#10 C:\xampp\htdocs\Autologs\framework\web\CController.php(265): SiteController->runActionWithFilters()
#11 C:\xampp\htdocs\Autologs\framework\web\CWebApplication.php(283): SiteController->run()
#12 C:\xampp\htdocs\Autologs\framework\web\CWebApplication.php(140): CWebApplication->runController()
#13 C:\xampp\htdocs\Autologs\framework\base\CApplication.php(180): CWebApplication->processRequest()
#14 C:\xampp\htdocs\Autologs\index.php(13): CWebApplication->run()
REQUEST_URI=/Autologs/index.php
in C:\xampp\htdocs\Autologs\protected\views\site\logtabs.php (8)
in C:\xampp\htdocs\Autologs\protected\views\site\index.php (11)
in C:\xampp\htdocs\Autologs\protected\controllers\SiteController.php (34)
2017/08/27 15:23:59 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '@gmail.com' at line 1. The SQL statement executed was: SELECT `appname`  FROM `tbuserapps` WHERE `userid`=ojwang.jacob@gmail.com.
in C:\xampp\htdocs\Autologs\protected\models\userapps.php (105)
in C:\xampp\htdocs\Autologs\protected\views\site\logtabs.php (5)
in C:\xampp\htdocs\Autologs\protected\views\site\index.php (11)
2017/08/27 15:23:59 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '@gmail.com' at line 1. The SQL statement executed was: SELECT `appname`  FROM `tbuserapps` WHERE `userid`=ojwang.jacob@gmail.com' in C:\xampp\htdocs\Autologs\framework\db\CDbCommand.php:543
Stack trace:
#0 C:\xampp\htdocs\Autologs\framework\db\CDbCommand.php(396): CDbCommand->queryInternal('fetchAll', Array, Array)
#1 C:\xampp\htdocs\Autologs\protected\models\userapps.php(105): CDbCommand->queryAll()
#2 C:\xampp\htdocs\Autologs\protected\views\site\logtabs.php(5): Userapps->searchApps()
#3 C:\xampp\htdocs\Autologs\framework\web\CBaseController.php(126): require('C:\xampp\htdocs...')
#4 C:\xampp\htdocs\Autologs\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\xampp\htdocs...', Array, true)
#5 C:\xampp\htdocs\Autologs\framework\web\CController.php(869): CBaseController->renderFile('C:\xampp\htdocs...', Array, true)
#6 C:\xampp\htdocs\Autologs\protected\views\site\index.php(11): CController->renderPartial('logtabs', Array)
#7 C:\xampp\htdocs\Autologs\framework\web\CBaseController.php(126): require('C:\xampp\htdocs...')
#8 C:\xampp\htdocs\Autologs\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\xampp\htdocs...', Array, true)
#9 C:\xampp\htdocs\Autologs\framework\web\CController.php(869): CBaseController->renderFile('C:\xampp\htdocs...', Array, true)
#10 C:\xampp\htdocs\Autologs\framework\web\CController.php(782): CController->renderPartial('index', Array, true)
#11 C:\xampp\htdocs\Autologs\protected\controllers\SiteController.php(34): CController->render('index', Array)
#12 C:\xampp\htdocs\Autologs\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#13 C:\xampp\htdocs\Autologs\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#14 C:\xampp\htdocs\Autologs\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#15 C:\xampp\htdocs\Autologs\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#16 C:\xampp\htdocs\Autologs\framework\web\CWebApplication.php(283): CController->run('')
#17 C:\xampp\htdocs\Autologs\framework\web\CWebApplication.php(140): CWebApplication->runController('')
#18 C:\xampp\htdocs\Autologs\framework\base\CApplication.php(180): CWebApplication->processRequest()
#19 C:\xampp\htdocs\Autologs\index.php(13): CApplication->run()
#20 {main}
REQUEST_URI=/Autologs/index.php
HTTP_REFERER=http://localhost/Autologs/index.php?r=site/login
---
2017/08/27 15:25:36 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '@gmail.com' at line 1. The SQL statement executed was: SELECT `appname`  FROM `tbuserapps` WHERE `userid`=ojwang.jacob@gmail.com.
in C:\xampp\htdocs\Autologs\protected\models\userapps.php (105)
in C:\xampp\htdocs\Autologs\protected\views\site\logtabs.php (5)
in C:\xampp\htdocs\Autologs\protected\views\site\index.php (11)
2017/08/27 15:25:36 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '@gmail.com' at line 1. The SQL statement executed was: SELECT `appname`  FROM `tbuserapps` WHERE `userid`=ojwang.jacob@gmail.com' in C:\xampp\htdocs\Autologs\framework\db\CDbCommand.php:543
Stack trace:
#0 C:\xampp\htdocs\Autologs\framework\db\CDbCommand.php(396): CDbCommand->queryInternal('fetchAll', Array, Array)
#1 C:\xampp\htdocs\Autologs\protected\models\userapps.php(105): CDbCommand->queryAll()
#2 C:\xampp\htdocs\Autologs\protected\views\site\logtabs.php(5): Userapps->searchApps()
#3 C:\xampp\htdocs\Autologs\framework\web\CBaseController.php(126): require('C:\xampp\htdocs...')
#4 C:\xampp\htdocs\Autologs\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\xampp\htdocs...', Array, true)
#5 C:\xampp\htdocs\Autologs\framework\web\CController.php(869): CBaseController->renderFile('C:\xampp\htdocs...', Array, true)
#6 C:\xampp\htdocs\Autologs\protected\views\site\index.php(11): CController->renderPartial('logtabs', Array)
#7 C:\xampp\htdocs\Autologs\framework\web\CBaseController.php(126): require('C:\xampp\htdocs...')
#8 C:\xampp\htdocs\Autologs\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\xampp\htdocs...', Array, true)
#9 C:\xampp\htdocs\Autologs\framework\web\CController.php(869): CBaseController->renderFile('C:\xampp\htdocs...', Array, true)
#10 C:\xampp\htdocs\Autologs\framework\web\CController.php(782): CController->renderPartial('index', Array, true)
#11 C:\xampp\htdocs\Autologs\protected\controllers\SiteController.php(34): CController->render('index', Array)
#12 C:\xampp\htdocs\Autologs\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#13 C:\xampp\htdocs\Autologs\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#14 C:\xampp\htdocs\Autologs\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#15 C:\xampp\htdocs\Autologs\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#16 C:\xampp\htdocs\Autologs\framework\web\CWebApplication.php(283): CController->run('')
#17 C:\xampp\htdocs\Autologs\framework\web\CWebApplication.php(140): CWebApplication->runController('')
#18 C:\xampp\htdocs\Autologs\framework\base\CApplication.php(180): CWebApplication->processRequest()
#19 C:\xampp\htdocs\Autologs\index.php(13): CApplication->run()
#20 {main}
REQUEST_URI=/Autologs/index.php
HTTP_REFERER=http://localhost/Autologs/index.php?r=site/login
---
2017/08/27 15:27:44 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '@gmail.com' at line 1. The SQL statement executed was: SELECT `appname`  FROM `tbuserapps` WHERE `userid`=ojwang.jacob@gmail.com.
in C:\xampp\htdocs\Autologs\protected\models\userapps.php (105)
in C:\xampp\htdocs\Autologs\protected\views\site\logtabs.php (5)
in C:\xampp\htdocs\Autologs\protected\views\site\index.php (11)
2017/08/27 15:27:44 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '@gmail.com' at line 1. The SQL statement executed was: SELECT `appname`  FROM `tbuserapps` WHERE `userid`=ojwang.jacob@gmail.com' in C:\xampp\htdocs\Autologs\framework\db\CDbCommand.php:543
Stack trace:
#0 C:\xampp\htdocs\Autologs\framework\db\CDbCommand.php(396): CDbCommand->queryInternal('fetchAll', Array, Array)
#1 C:\xampp\htdocs\Autologs\protected\models\userapps.php(105): CDbCommand->queryAll()
#2 C:\xampp\htdocs\Autologs\protected\views\site\logtabs.php(5): Userapps->searchApps()
#3 C:\xampp\htdocs\Autologs\framework\web\CBaseController.php(126): require('C:\xampp\htdocs...')
#4 C:\xampp\htdocs\Autologs\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\xampp\htdocs...', Array, true)
#5 C:\xampp\htdocs\Autologs\framework\web\CController.php(869): CBaseController->renderFile('C:\xampp\htdocs...', Array, true)
#6 C:\xampp\htdocs\Autologs\protected\views\site\index.php(11): CController->renderPartial('logtabs', Array)
#7 C:\xampp\htdocs\Autologs\framework\web\CBaseController.php(126): require('C:\xampp\htdocs...')
#8 C:\xampp\htdocs\Autologs\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\xampp\htdocs...', Array, true)
#9 C:\xampp\htdocs\Autologs\framework\web\CController.php(869): CBaseController->renderFile('C:\xampp\htdocs...', Array, true)
#10 C:\xampp\htdocs\Autologs\framework\web\CController.php(782): CController->renderPartial('index', Array, true)
#11 C:\xampp\htdocs\Autologs\protected\controllers\SiteController.php(34): CController->render('index', Array)
#12 C:\xampp\htdocs\Autologs\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#13 C:\xampp\htdocs\Autologs\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#14 C:\xampp\htdocs\Autologs\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#15 C:\xampp\htdocs\Autologs\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#16 C:\xampp\htdocs\Autologs\framework\web\CWebApplication.php(283): CController->run('')
#17 C:\xampp\htdocs\Autologs\framework\web\CWebApplication.php(140): CWebApplication->runController('')
#18 C:\xampp\htdocs\Autologs\framework\base\CApplication.php(180): CWebApplication->processRequest()
#19 C:\xampp\htdocs\Autologs\index.php(13): CApplication->run()
#20 {main}
REQUEST_URI=/Autologs/index.php
HTTP_REFERER=http://localhost/Autologs/index.php?r=site/login
---
2017/08/27 15:34:53 [error] [exception.CException] exception 'CException' with message 'CWebApplication and its behaviors do not have a method or closure named "getState".' in C:\xampp\htdocs\Autologs\framework\base\CComponent.php:266
Stack trace:
#0 C:\xampp\htdocs\Autologs\protected\models\userapps.php(101): CComponent->__call('getState', Array)
#1 C:\xampp\htdocs\Autologs\protected\models\userapps.php(101): CWebApplication->getState('userid')
#2 C:\xampp\htdocs\Autologs\protected\views\site\logtabs.php(5): Userapps->searchApps()
#3 C:\xampp\htdocs\Autologs\framework\web\CBaseController.php(126): require('C:\xampp\htdocs...')
#4 C:\xampp\htdocs\Autologs\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\xampp\htdocs...', Array, true)
#5 C:\xampp\htdocs\Autologs\framework\web\CController.php(869): CBaseController->renderFile('C:\xampp\htdocs...', Array, true)
#6 C:\xampp\htdocs\Autologs\protected\views\site\index.php(11): CController->renderPartial('logtabs', Array)
#7 C:\xampp\htdocs\Autologs\framework\web\CBaseController.php(126): require('C:\xampp\htdocs...')
#8 C:\xampp\htdocs\Autologs\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\xampp\htdocs...', Array, true)
#9 C:\xampp\htdocs\Autologs\framework\web\CController.php(869): CBaseController->renderFile('C:\xampp\htdocs...', Array, true)
#10 C:\xampp\htdocs\Autologs\framework\web\CController.php(782): CController->renderPartial('index', Array, true)
#11 C:\xampp\htdocs\Autologs\protected\controllers\SiteController.php(33): CController->render('index', Array)
#12 C:\xampp\htdocs\Autologs\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#13 C:\xampp\htdocs\Autologs\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#14 C:\xampp\htdocs\Autologs\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#15 C:\xampp\htdocs\Autologs\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#16 C:\xampp\htdocs\Autologs\framework\web\CWebApplication.php(283): CController->run('')
#17 C:\xampp\htdocs\Autologs\framework\web\CWebApplication.php(140): CWebApplication->runController('')
#18 C:\xampp\htdocs\Autologs\framework\base\CApplication.php(180): CWebApplication->processRequest()
#19 C:\xampp\htdocs\Autologs\index.php(13): CApplication->run()
#20 {main}
REQUEST_URI=/Autologs/index.php
HTTP_REFERER=http://localhost/Autologs/index.php?r=site/login
---
2017/08/27 15:36:08 [error] [php] Array to string conversion (C:\xampp\htdocs\Autologs\protected\views\site\logtabs.php:11)
Stack trace:
#0 C:\xampp\htdocs\Autologs\framework\web\CController.php(869): SiteController->renderFile()
#1 C:\xampp\htdocs\Autologs\protected\views\site\index.php(11): SiteController->renderPartial()
#2 C:\xampp\htdocs\Autologs\framework\web\CBaseController.php(126): require()
#3 C:\xampp\htdocs\Autologs\framework\web\CBaseController.php(95): SiteController->renderInternal()
#4 C:\xampp\htdocs\Autologs\framework\web\CController.php(869): SiteController->renderFile()
#5 C:\xampp\htdocs\Autologs\framework\web\CController.php(782): SiteController->renderPartial()
#6 C:\xampp\htdocs\Autologs\protected\controllers\SiteController.php(33): SiteController->render()
#7 C:\xampp\htdocs\Autologs\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#8 C:\xampp\htdocs\Autologs\framework\web\CController.php(308): CInlineAction->runWithParams()
#9 C:\xampp\htdocs\Autologs\framework\web\CController.php(286): SiteController->runAction()
#10 C:\xampp\htdocs\Autologs\framework\web\CController.php(265): SiteController->runActionWithFilters()
#11 C:\xampp\htdocs\Autologs\framework\web\CWebApplication.php(283): SiteController->run()
#12 C:\xampp\htdocs\Autologs\framework\web\CWebApplication.php(140): CWebApplication->runController()
#13 C:\xampp\htdocs\Autologs\framework\base\CApplication.php(180): CWebApplication->processRequest()
#14 C:\xampp\htdocs\Autologs\index.php(13): CWebApplication->run()
REQUEST_URI=/Autologs/index.php
in C:\xampp\htdocs\Autologs\protected\views\site\logtabs.php (11)
in C:\xampp\htdocs\Autologs\protected\views\site\index.php (11)
in C:\xampp\htdocs\Autologs\protected\controllers\SiteController.php (33)
2017/08/27 15:39:27 [error] [php] Undefined variable: users (C:\xampp\htdocs\Autologs\protected\models\userapps.php:106)
Stack trace:
#0 C:\xampp\htdocs\Autologs\framework\web\CBaseController.php(95): SiteController->renderInternal()
#1 C:\xampp\htdocs\Autologs\framework\web\CController.php(869): SiteController->renderFile()
#2 C:\xampp\htdocs\Autologs\protected\views\site\index.php(11): SiteController->renderPartial()
#3 C:\xampp\htdocs\Autologs\framework\web\CBaseController.php(126): require()
#4 C:\xampp\htdocs\Autologs\framework\web\CBaseController.php(95): SiteController->renderInternal()
#5 C:\xampp\htdocs\Autologs\framework\web\CController.php(869): SiteController->renderFile()
#6 C:\xampp\htdocs\Autologs\framework\web\CController.php(782): SiteController->renderPartial()
#7 C:\xampp\htdocs\Autologs\protected\controllers\SiteController.php(33): SiteController->render()
#8 C:\xampp\htdocs\Autologs\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#9 C:\xampp\htdocs\Autologs\framework\web\CController.php(308): CInlineAction->runWithParams()
#10 C:\xampp\htdocs\Autologs\framework\web\CController.php(286): SiteController->runAction()
#11 C:\xampp\htdocs\Autologs\framework\web\CController.php(265): SiteController->runActionWithFilters()
#12 C:\xampp\htdocs\Autologs\framework\web\CWebApplication.php(283): SiteController->run()
#13 C:\xampp\htdocs\Autologs\framework\web\CWebApplication.php(140): CWebApplication->runController()
#14 C:\xampp\htdocs\Autologs\framework\base\CApplication.php(180): CWebApplication->processRequest()
#15 C:\xampp\htdocs\Autologs\index.php(13): CWebApplication->run()
REQUEST_URI=/Autologs/index.php
in C:\xampp\htdocs\Autologs\protected\models\userapps.php (106)
in C:\xampp\htdocs\Autologs\protected\views\site\logtabs.php (5)
in C:\xampp\htdocs\Autologs\protected\views\site\index.php (11)
2017/08/27 15:43:00 [error] [php] Undefined variable: app (C:\xampp\htdocs\Autologs\protected\views\site\logs.php:19)
Stack trace:
#0 C:\xampp\htdocs\Autologs\framework\web\CController.php(869): SiteController->renderFile()
#1 C:\xampp\htdocs\Autologs\protected\views\site\logtabs.php(14): SiteController->renderPartial()
#2 C:\xampp\htdocs\Autologs\framework\web\CBaseController.php(126): require()
#3 C:\xampp\htdocs\Autologs\framework\web\CBaseController.php(95): SiteController->renderInternal()
#4 C:\xampp\htdocs\Autologs\framework\web\CController.php(869): SiteController->renderFile()
#5 C:\xampp\htdocs\Autologs\protected\views\site\index.php(11): SiteController->renderPartial()
#6 C:\xampp\htdocs\Autologs\framework\web\CBaseController.php(126): require()
#7 C:\xampp\htdocs\Autologs\framework\web\CBaseController.php(95): SiteController->renderInternal()
#8 C:\xampp\htdocs\Autologs\framework\web\CController.php(869): SiteController->renderFile()
#9 C:\xampp\htdocs\Autologs\framework\web\CController.php(782): SiteController->renderPartial()
#10 C:\xampp\htdocs\Autologs\protected\controllers\SiteController.php(33): SiteController->render()
#11 C:\xampp\htdocs\Autologs\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#12 C:\xampp\htdocs\Autologs\framework\web\CController.php(308): CInlineAction->runWithParams()
#13 C:\xampp\htdocs\Autologs\framework\web\CController.php(286): SiteController->runAction()
#14 C:\xampp\htdocs\Autologs\framework\web\CController.php(265): SiteController->runActionWithFilters()
#15 C:\xampp\htdocs\Autologs\framework\web\CWebApplication.php(283): SiteController->run()
#16 C:\xampp\htdocs\Autologs\framework\web\CWebApplication.php(140): CWebApplication->runController()
#17 C:\xampp\htdocs\Autologs\framework\base\CApplication.php(180): CWebApplication->processRequest()
#18 C:\xampp\htdocs\Autologs\index.php(13): CWebApplication->run()
REQUEST_URI=/Autologs/index.php
in C:\xampp\htdocs\Autologs\protected\views\site\logs.php (19)
in C:\xampp\htdocs\Autologs\protected\views\site\logtabs.php (14)
in C:\xampp\htdocs\Autologs\protected\views\site\index.php (11)
2017/08/27 20:09:14 [error] [php] Undefined variable: scoketdata (C:\xampp\htdocs\Autologs\protected\views\site\logs.php:54)
Stack trace:
#0 C:\xampp\htdocs\Autologs\framework\web\CController.php(869): SiteController->renderFile()
#1 C:\xampp\htdocs\Autologs\protected\views\site\logtabs.php(14): SiteController->renderPartial()
#2 C:\xampp\htdocs\Autologs\framework\web\CBaseController.php(126): require()
#3 C:\xampp\htdocs\Autologs\framework\web\CBaseController.php(95): SiteController->renderInternal()
#4 C:\xampp\htdocs\Autologs\framework\web\CController.php(869): SiteController->renderFile()
#5 C:\xampp\htdocs\Autologs\protected\views\site\index.php(18): SiteController->renderPartial()
#6 C:\xampp\htdocs\Autologs\framework\web\CBaseController.php(126): require()
#7 C:\xampp\htdocs\Autologs\framework\web\CBaseController.php(95): SiteController->renderInternal()
#8 C:\xampp\htdocs\Autologs\framework\web\CController.php(869): SiteController->renderFile()
#9 C:\xampp\htdocs\Autologs\framework\web\CController.php(782): SiteController->renderPartial()
#10 C:\xampp\htdocs\Autologs\protected\controllers\SiteController.php(33): SiteController->render()
#11 C:\xampp\htdocs\Autologs\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#12 C:\xampp\htdocs\Autologs\framework\web\CController.php(308): CInlineAction->runWithParams()
#13 C:\xampp\htdocs\Autologs\framework\web\CController.php(286): SiteController->runAction()
#14 C:\xampp\htdocs\Autologs\framework\web\CController.php(265): SiteController->runActionWithFilters()
#15 C:\xampp\htdocs\Autologs\framework\web\CWebApplication.php(283): SiteController->run()
#16 C:\xampp\htdocs\Autologs\framework\web\CWebApplication.php(140): CWebApplication->runController()
#17 C:\xampp\htdocs\Autologs\framework\base\CApplication.php(180): CWebApplication->processRequest()
#18 C:\xampp\htdocs\Autologs\index.php(13): CWebApplication->run()
REQUEST_URI=/Autologs/index.php
in C:\xampp\htdocs\Autologs\protected\views\site\logs.php (54)
in C:\xampp\htdocs\Autologs\protected\views\site\logtabs.php (14)
in C:\xampp\htdocs\Autologs\protected\views\site\index.php (18)
2017/08/27 20:26:26 [error] [php] Undefined variable: input (C:\xampp\htdocs\Autologs\protected\views\site\logs.php:54)
Stack trace:
#0 C:\xampp\htdocs\Autologs\framework\web\CController.php(869): SiteController->renderFile()
#1 C:\xampp\htdocs\Autologs\protected\views\site\logtabs.php(14): SiteController->renderPartial()
#2 C:\xampp\htdocs\Autologs\framework\web\CBaseController.php(126): require()
#3 C:\xampp\htdocs\Autologs\framework\web\CBaseController.php(95): SiteController->renderInternal()
#4 C:\xampp\htdocs\Autologs\framework\web\CController.php(869): SiteController->renderFile()
#5 C:\xampp\htdocs\Autologs\protected\views\site\index.php(18): SiteController->renderPartial()
#6 C:\xampp\htdocs\Autologs\framework\web\CBaseController.php(126): require()
#7 C:\xampp\htdocs\Autologs\framework\web\CBaseController.php(95): SiteController->renderInternal()
#8 C:\xampp\htdocs\Autologs\framework\web\CController.php(869): SiteController->renderFile()
#9 C:\xampp\htdocs\Autologs\framework\web\CController.php(782): SiteController->renderPartial()
#10 C:\xampp\htdocs\Autologs\protected\controllers\SiteController.php(33): SiteController->render()
#11 C:\xampp\htdocs\Autologs\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#12 C:\xampp\htdocs\Autologs\framework\web\CController.php(308): CInlineAction->runWithParams()
#13 C:\xampp\htdocs\Autologs\framework\web\CController.php(286): SiteController->runAction()
#14 C:\xampp\htdocs\Autologs\framework\web\CController.php(265): SiteController->runActionWithFilters()
#15 C:\xampp\htdocs\Autologs\framework\web\CWebApplication.php(283): SiteController->run()
#16 C:\xampp\htdocs\Autologs\framework\web\CWebApplication.php(140): CWebApplication->runController()
#17 C:\xampp\htdocs\Autologs\framework\base\CApplication.php(180): CWebApplication->processRequest()
#18 C:\xampp\htdocs\Autologs\index.php(13): CWebApplication->run()
REQUEST_URI=/Autologs/index.php?r=site/index
in C:\xampp\htdocs\Autologs\protected\views\site\logs.php (54)
in C:\xampp\htdocs\Autologs\protected\views\site\logtabs.php (14)
in C:\xampp\htdocs\Autologs\protected\views\site\index.php (18)
2017/09/09 23:23:45 [error] [php] Undefined index: frmuploadMedia (C:\xampp\htdocs\Autologs\protected\controllers\TransactionsController.php:7)
Stack trace:
#0 C:\xampp\htdocs\Autologs\framework\web\CController.php(286): TransactionsController->runAction()
#1 C:\xampp\htdocs\Autologs\framework\web\CController.php(265): TransactionsController->runActionWithFilters()
#2 C:\xampp\htdocs\Autologs\framework\web\CWebApplication.php(283): TransactionsController->run()
#3 C:\xampp\htdocs\Autologs\framework\web\CWebApplication.php(140): CWebApplication->runController()
#4 C:\xampp\htdocs\Autologs\framework\base\CApplication.php(180): CWebApplication->processRequest()
#5 C:\xampp\htdocs\Autologs\index.php(13): CWebApplication->run()
REQUEST_URI=/Autologs/index.php?r=Transactions/index&view=about
in C:\xampp\htdocs\Autologs\protected\controllers\TransactionsController.php (7)
in C:\xampp\htdocs\Autologs\index.php (13)
2017/09/09 23:42:20 [error] [php] file_get_contents(main.js): failed to open stream: No such file or directory (C:\xampp\htdocs\Autologs\protected\controllers\TransactionsController.php:9)
Stack trace:
#0 C:\xampp\htdocs\Autologs\framework\web\CController.php(308): CInlineAction->runWithParams()
#1 C:\xampp\htdocs\Autologs\framework\web\CController.php(286): TransactionsController->runAction()
#2 C:\xampp\htdocs\Autologs\framework\web\CController.php(265): TransactionsController->runActionWithFilters()
#3 C:\xampp\htdocs\Autologs\framework\web\CWebApplication.php(283): TransactionsController->run()
#4 C:\xampp\htdocs\Autologs\framework\web\CWebApplication.php(140): CWebApplication->runController()
#5 C:\xampp\htdocs\Autologs\framework\base\CApplication.php(180): CWebApplication->processRequest()
#6 C:\xampp\htdocs\Autologs\index.php(13): CWebApplication->run()
REQUEST_URI=/Autologs/index.php?r=Transactions/index
in C:\xampp\htdocs\Autologs\protected\controllers\TransactionsController.php (9)
in C:\xampp\htdocs\Autologs\index.php (13)
2017/09/09 23:42:46 [error] [php] file_get_contents() expects parameter 1 to be a valid path, array given (C:\xampp\htdocs\Autologs\protected\controllers\TransactionsController.php:9)
Stack trace:
#0 C:\xampp\htdocs\Autologs\framework\web\CController.php(308): CInlineAction->runWithParams()
#1 C:\xampp\htdocs\Autologs\framework\web\CController.php(286): TransactionsController->runAction()
#2 C:\xampp\htdocs\Autologs\framework\web\CController.php(265): TransactionsController->runActionWithFilters()
#3 C:\xampp\htdocs\Autologs\framework\web\CWebApplication.php(283): TransactionsController->run()
#4 C:\xampp\htdocs\Autologs\framework\web\CWebApplication.php(140): CWebApplication->runController()
#5 C:\xampp\htdocs\Autologs\framework\base\CApplication.php(180): CWebApplication->processRequest()
#6 C:\xampp\htdocs\Autologs\index.php(13): CWebApplication->run()
REQUEST_URI=/Autologs/index.php?r=Transactions/index
in C:\xampp\htdocs\Autologs\protected\controllers\TransactionsController.php (9)
in C:\xampp\htdocs\Autologs\index.php (13)
2017/09/09 23:53:24 [error] [php] Undefined variable: fileContents (C:\xampp\htdocs\Autologs\protected\controllers\TransactionsController.php:10)
Stack trace:
#0 C:\xampp\htdocs\Autologs\framework\web\CController.php(286): TransactionsController->runAction()
#1 C:\xampp\htdocs\Autologs\framework\web\CController.php(265): TransactionsController->runActionWithFilters()
#2 C:\xampp\htdocs\Autologs\framework\web\CWebApplication.php(283): TransactionsController->run()
#3 C:\xampp\htdocs\Autologs\framework\web\CWebApplication.php(140): CWebApplication->runController()
#4 C:\xampp\htdocs\Autologs\framework\base\CApplication.php(180): CWebApplication->processRequest()
#5 C:\xampp\htdocs\Autologs\index.php(13): CWebApplication->run()
REQUEST_URI=/Autologs/index.php?r=Transactions/index
in C:\xampp\htdocs\Autologs\protected\controllers\TransactionsController.php (10)
in C:\xampp\htdocs\Autologs\index.php (13)
2017/09/09 23:53:57 [error] [php] Undefined variable: fileContents (C:\xampp\htdocs\Autologs\protected\views\transactions\index.php:33)
Stack trace:
#0 C:\xampp\htdocs\Autologs\framework\web\CController.php(869): TransactionsController->renderFile()
#1 C:\xampp\htdocs\Autologs\framework\web\CController.php(782): TransactionsController->renderPartial()
#2 C:\xampp\htdocs\Autologs\protected\controllers\TransactionsController.php(12): TransactionsController->render()
#3 C:\xampp\htdocs\Autologs\framework\web\actions\CInlineAction.php(49): TransactionsController->actionIndex()
#4 C:\xampp\htdocs\Autologs\framework\web\CController.php(308): CInlineAction->runWithParams()
#5 C:\xampp\htdocs\Autologs\framework\web\CController.php(286): TransactionsController->runAction()
#6 C:\xampp\htdocs\Autologs\framework\web\CController.php(265): TransactionsController->runActionWithFilters()
#7 C:\xampp\htdocs\Autologs\framework\web\CWebApplication.php(283): TransactionsController->run()
#8 C:\xampp\htdocs\Autologs\framework\web\CWebApplication.php(140): CWebApplication->runController()
#9 C:\xampp\htdocs\Autologs\framework\base\CApplication.php(180): CWebApplication->processRequest()
#10 C:\xampp\htdocs\Autologs\index.php(13): CWebApplication->run()
REQUEST_URI=/Autologs/index.php?r=Transactions/index
in C:\xampp\htdocs\Autologs\protected\views\transactions\index.php (33)
in C:\xampp\htdocs\Autologs\protected\controllers\TransactionsController.php (12)
in C:\xampp\htdocs\Autologs\index.php (13)
2017/09/10 00:03:00 [error] [php] Undefined variable: fileContents (C:\xampp\htdocs\Autologs\protected\views\transactions\index.php:64)
Stack trace:
#0 C:\xampp\htdocs\Autologs\framework\web\CController.php(869): TransactionsController->renderFile()
#1 C:\xampp\htdocs\Autologs\framework\web\CController.php(782): TransactionsController->renderPartial()
#2 C:\xampp\htdocs\Autologs\protected\controllers\TransactionsController.php(12): TransactionsController->render()
#3 C:\xampp\htdocs\Autologs\framework\web\actions\CInlineAction.php(49): TransactionsController->actionIndex()
#4 C:\xampp\htdocs\Autologs\framework\web\CController.php(308): CInlineAction->runWithParams()
#5 C:\xampp\htdocs\Autologs\framework\web\CController.php(286): TransactionsController->runAction()
#6 C:\xampp\htdocs\Autologs\framework\web\CController.php(265): TransactionsController->runActionWithFilters()
#7 C:\xampp\htdocs\Autologs\framework\web\CWebApplication.php(283): TransactionsController->run()
#8 C:\xampp\htdocs\Autologs\framework\web\CWebApplication.php(140): CWebApplication->runController()
#9 C:\xampp\htdocs\Autologs\framework\base\CApplication.php(180): CWebApplication->processRequest()
#10 C:\xampp\htdocs\Autologs\index.php(13): CWebApplication->run()
REQUEST_URI=/Autologs/index.php?r=Transactions/index
in C:\xampp\htdocs\Autologs\protected\views\transactions\index.php (64)
in C:\xampp\htdocs\Autologs\protected\controllers\TransactionsController.php (12)
in C:\xampp\htdocs\Autologs\index.php (13)
2017/09/10 00:03:06 [error] [php] Undefined variable: fileContents (C:\xampp\htdocs\Autologs\protected\views\transactions\index.php:64)
Stack trace:
#0 C:\xampp\htdocs\Autologs\framework\web\CController.php(869): TransactionsController->renderFile()
#1 C:\xampp\htdocs\Autologs\framework\web\CController.php(782): TransactionsController->renderPartial()
#2 C:\xampp\htdocs\Autologs\protected\controllers\TransactionsController.php(12): TransactionsController->render()
#3 C:\xampp\htdocs\Autologs\framework\web\actions\CInlineAction.php(49): TransactionsController->actionIndex()
#4 C:\xampp\htdocs\Autologs\framework\web\CController.php(308): CInlineAction->runWithParams()
#5 C:\xampp\htdocs\Autologs\framework\web\CController.php(286): TransactionsController->runAction()
#6 C:\xampp\htdocs\Autologs\framework\web\CController.php(265): TransactionsController->runActionWithFilters()
#7 C:\xampp\htdocs\Autologs\framework\web\CWebApplication.php(283): TransactionsController->run()
#8 C:\xampp\htdocs\Autologs\framework\web\CWebApplication.php(140): CWebApplication->runController()
#9 C:\xampp\htdocs\Autologs\framework\base\CApplication.php(180): CWebApplication->processRequest()
#10 C:\xampp\htdocs\Autologs\index.php(13): CWebApplication->run()
REQUEST_URI=/Autologs/index.php?r=Transactions/index
in C:\xampp\htdocs\Autologs\protected\views\transactions\index.php (64)
in C:\xampp\htdocs\Autologs\protected\controllers\TransactionsController.php (12)
in C:\xampp\htdocs\Autologs\index.php (13)
2017/09/11 19:31:10 [error] [exception.CDbException] CDbException: CDbConnection failed to open the DB connection: SQLSTATE[HY000] [2002] No connection could be made because the target machine actively refused it.
 in C:\Apache24\htdocs\Autologs\framework\db\CDbConnection.php:382
Stack trace:
#0 C:\Apache24\htdocs\Autologs\framework\db\CDbConnection.php(330): CDbConnection->open()
#1 C:\Apache24\htdocs\Autologs\framework\db\CDbConnection.php(308): CDbConnection->setActive(true)
#2 C:\Apache24\htdocs\Autologs\framework\base\CModule.php(387): CDbConnection->init()
#3 C:\Apache24\htdocs\Autologs\framework\base\CApplication.php(450): CModule->getComponent('db')
#4 C:\Apache24\htdocs\Autologs\framework\db\ar\CActiveRecord.php(634): CApplication->getDb()
#5 C:\Apache24\htdocs\Autologs\framework\db\ar\CActiveRecord.php(2361): CActiveRecord->getDbConnection()
#6 C:\Apache24\htdocs\Autologs\framework\db\ar\CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(Userapps))
#7 C:\Apache24\htdocs\Autologs\framework\db\ar\CActiveRecord.php(79): CActiveRecord->getMetaData()
#8 C:\Apache24\htdocs\Autologs\protected\controllers\SiteController.php(32): CActiveRecord->__construct()
#9 C:\Apache24\htdocs\Autologs\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#10 C:\Apache24\htdocs\Autologs\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#11 C:\Apache24\htdocs\Autologs\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#12 C:\Apache24\htdocs\Autologs\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#13 C:\Apache24\htdocs\Autologs\framework\web\CWebApplication.php(283): CController->run('')
#14 C:\Apache24\htdocs\Autologs\framework\web\CWebApplication.php(140): CWebApplication->runController('')
#15 C:\Apache24\htdocs\Autologs\framework\base\CApplication.php(180): CWebApplication->processRequest()
#16 C:\Apache24\htdocs\Autologs\index.php(13): CApplication->run()
#17 {main}
REQUEST_URI=/Autologs/
---
